import SwiftUI

struct Version {
    var version: String
    var date: String
    var changes: [String]
}

// swiftlint:disable line_length
private let versions = [
    Version(version: "0.218.0", date: "2024-03-27", changes: [
        "• Use personal voice in chat text to speech toggle.",
        "  • Disables language detection per message.",
    ]),
    Version(version: "0.217.0", date: "2024-03-26", changes: [
        "• Toggle to prefer high quality text to speech voices (Premium > Enhanced > Default). 💡 nn2p",
        "  • Install high quality voices in iOS settings (Accessibility → VoiceOver → Speech → Voice).",
    ]),
    Version(version: "0.216.0", date: "2024-03-26", changes: [
        "• Chat text to speech settings.",
        "  • Detect language per message toggle.",
        "  • Say username toggle.",
        "  • Preferred gender (Unspecified/Male/Female).",
        "    • Many languages only have one gender.",
        "  • Rate.",
        "  • Volume.",
    ]),
    Version(version: "0.215.0", date: "2024-03-25", changes: [
        "• Optional chat text to speech (TTS).",
        "• Spanish translation updated. ✍️ adriportela95",
        "• Ukrainian translation updated. ✍️ Maksym",
    ]),
    Version(version: "0.214.0", date: "2024-03-25", changes: [
        "• Limit recording to two channels. 🐛 ariathome",
        "  • So it can record, but likely without audio. To be continued.",
        "• Korean translation updated. ✍️ 고블린",
        "• Watch companion app.",
        "  • Improve state synchronization between watch and phone.",
    ]),
    Version(version: "0.213.0", date: "2024-03-24", changes: [
        "• Use numbers and punctuation keyboard where applicable.",
        "• Watch companion app.",
        "  • Start and stop recording.",
    ]),
    Version(version: "0.212.0", date: "2024-03-24", changes: [
        "• Make crop widgets work without source widget added to the scene.",
        "• Quick buttons names styling.",
    ]),
    Version(version: "0.211.0", date: "2024-03-23", changes: [
        "• Ukrainian translation started. 💡 Maksym",
        "• Try to fix app hangs when changing to some camera settings. 🐛 Tony Mah",
        "  • For example Apple Log and 120 FPS.",
        "• Remove 120 FPS for now as it made the app crash more frequently than other FPSs.",
        "• Crop widget. 💡 Tony Mah",
        "  • Can only use a browser widget as source for now.",
        "• German translation updated. ✍️ MaurisonX",
        "• Open Streaming Platform chat continued. Works now? 🐛 ErAzOr",
    ]),
    Version(version: "0.210.0", date: "2024-03-22", changes: [
        "• 120 FPS (for devices that supports it). 💡 Tony Mah",
        "• Try to make speed units more universal. 🐛 Murrito",
        "• Watch companion app.",
        "  • Go live and end stream toggle. 💡 BoostedBen",
    ]),
    Version(version: "0.209.0", date: "2024-03-21", changes: [
        "• Support for more LUT formats.",
        "  • 16 bits per pixel component, not only 8.",
        "  • RGB, not only RGBA.",
        "• Fix/mitigate slow/hanging video settings changes. 🐛 JohannesLiv",
        "  • Sometimes still problematic when torch is on.",
    ]),
    Version(version: "0.208.0", date: "2024-03-19", changes: [
        "• Fix Apple Log, and more specifically apply LUTs correctly. 🐛 JohannesLiv",
        "• Fix vertical lines and other image artifacts when applying various effects/widgets/draw on stream. 🐛 JohannesLiv",
    ]),
    Version(version: "0.207.0", date: "2024-03-18", changes: [
        "• Updated Russian translation. ✍️ Murrito",
    ]),
    Version(version: "0.206.0", date: "2024-03-18", changes: [
        "• Fix OBS media source button to hopefully fix audio and video issues.",
        "  • Similar to `!fix` in NOALBS.",
    ]),
    Version(version: "0.205.0", date: "2024-03-18", changes: [
        "• Show cosmetics page when tapping the Moblin icon.",
        "• Partially fix LUTs.",
        "  • Not oversaturated anymore, but still vertical lines sometimes.",
        "• Fix zoom preset and scene selection pickers when button shapes are enabled. 🐛 Tony Mah",
    ]),
    Version(version: "0.204.0", date: "2024-03-17", changes: [
        "• Untested Open Streaming Platform chat using websockets. 💡 ErAzOr",
        "  • Settings → Streams → My stream → Open Streaming Platform.",
    ]),
    Version(version: "0.203.2", date: "2024-03-16", changes: [
        "• Fix torch when switching from back to front camera (or at least fix major bug).",
    ]),
    Version(version: "0.203.1", date: "2024-03-16", changes: [
        "• Fix 0.5x zoom preset for front camera.",
    ]),
    Version(version: "0.203.0", date: "2024-03-16", changes: [
        "• Select wide dual back camera by default if triple camera does not exist. 🐛 breakJ and nezst",
        "  • Should make 0.5x lens show up by default on some phone models.",
    ]),
    Version(version: "0.202.0", date: "2024-03-15", changes: [
        "• Fix streaming history crash. 🐛 MrPol",
    ]),
    Version(version: "0.201.0", date: "2024-03-15", changes: [
        "• Slightly bigger and always dark color theme zoom preset and scene selection pickers.",
    ]),
    Version(version: "0.200.0", date: "2024-03-14", changes: [
        "• Make remote control assistant listen on all interfaces.",
        "• Show list of remote control assistant URLs.",
    ]),
    Version(version: "0.199.0", date: "2024-03-13", changes: [
        "• Always show Personal Hotspot RTMP URL in RTMP server stream settings. 💡 vi",
        "  • Kind of experimental. Works on my phone.",
        "• Only show RTMP publish URLs when RTMP server is enabled.",
        "• Disable audio bitrate setting when live.",
        "• Toggle to enable/disable connection priorities in remote control. 💡 djandrea.",
    ]),
    Version(version: "0.198.0", date: "2024-03-12", changes: [
        "• Watch companion app.",
        "  • Show emotes immediately. No Moblin icon placeholder.",
    ]),
    Version(version: "0.197.0", date: "2024-03-12", changes: [
        "• Watch companion app.",
        "  • Show emotes. Fetches slowly. To be improved.",
        "  • Fix freezes (as in no new chat messages in a few minutes).",
    ]),
    Version(version: "0.196.0", date: "2024-03-11", changes: [
        "• Helpful message when trying to add a widget to a scene when no widgets exists.",
        "• Fix crash when entering negative height or width for a browser widget. 🐛 Onur",
        "• Updated Spanish translation. ✍️ adriportela95",
        "• Updated German translation. ✍️ MaurisonX",
    ]),
    Version(version: "0.195.0", date: "2024-03-11", changes: [
        "• Make manual focus slider follow auto focus. 💡 Tony Mah",
    ]),
    Version(version: "0.194.0", date: "2024-03-10", changes: [
        "• Change recordings icon in settings to the same icon as the recordings quick button.",
        "• Add SRT connection priorities to remote control. 💡 djandrea.",
        "  • UI is not updated if on connection priorities page.",
        "• Manual focus for cameras that supports it (non-triple/dual). 💡 b3ck and others",
        "  • Press the \"Camera\" quick button to set focus.",
        "    • If not showing, toggle it on in Settings → Display → Quick buttons.",
        "• Watch companion app.",
        "  • Disable chat emotes as they make the app crash now. Maybe started to crash after watchOS update?",
        "• Fix chat disappearing. 🐛 ariathome and onigiri",
        "  • Was mainly a problem with small chat window and long chat messages.",
        "• Camera selection per scene. 💡 JohannesLiv",
        "  • Removed Setttings → Camera → Back/Front. Select camera in Settings → Scenes → My scene instead.",
    ]),
    Version(version: "0.193.0", date: "2024-03-07", changes: [
        "• Watch companion app.",
        "  • Lower preview quality as it seems to work better.",
        "    • A preview image sent from phone to watch is about 10k bytes now.",
        "  • Increase maximum number of chat messages from 10 to 20.",
    ]),
    Version(version: "0.192.0", date: "2024-03-06", changes: [
        "• Show error toast if LUT image is invalid.",
        "• Fix empty ethernet interface name. 🐛 Marlow",
        "  • Only works for unrecognized network interfaces (those not in Settings → Display → Network interface names).",
        "• Watch companion app.",
        "  • Chat improvements.",
        "    • Show number of discarded messages.",
        "    • Show when reconnected to phone.",
        "    • Remove duplicated spaces between words.",
    ]),
    Version(version: "0.191.0", date: "2024-03-05", changes: [
        "• Watch companion app.",
        "  • Some logs and counters for debugging.",
        "  • Settings tab mostly for debug.",
        "• Tub icon.",
    ]),
    Version(version: "0.190.0", date: "2024-03-04", changes: [
        "• Icons next to text in main settings page.",
        "• Move chat settings to main settings page.",
        "• Watch companion app.",
        "  • Red line to separate new from old messages.",
    ]),
    Version(version: "0.189.0", date: "2024-03-04", changes: [
        "• Watch companion app.",
        "  • Optional watch face complication.",
        "    • Acts as a shortcut to open the app.",
    ]),
    Version(version: "0.188.0", date: "2024-03-03", changes: [
        "• List of usernames to ignore chat messages from. 💡 ichrisIRL",
        "  • Settings → Display → Chat → Usernames to ignore",
        "• Watch companion app.",
        "  • Only play chat message notification if no messages has been received in 30 seconds. 💡 JohannesLiv",
        "• Make Mac app lists mics again (and use?).",
    ]),
    Version(version: "0.187.0", date: "2024-03-03", changes: [
        "• Watch companion app.",
        "  • Improved robustness.",
        "  • Toggle to enable/disable notification as sound and vibration on each chat message.",
        "    • App must be in foreground for it to work.",
    ]),
    Version(version: "0.186.0", date: "2024-03-02", changes: [
        "• Watch companion app.",
        "  • Chat emotes (not all image formats are supported).",
        "  • Setting to hide/show timestamps.",
    ]),
    Version(version: "0.185.0", date: "2024-03-02", changes: [
        "• Watch companion app.",
        "  • Configurable chat font size.",
        "    • Configure in phone app: Settings → Watch → Chat",
        "  • Show disconnected icon overlay when disconnected from phone.",
        "  • Show at most 5 chat messages per second.",
        "    • Chat messages will be discarded when received at higher pace.",
    ]),
    Version(version: "0.184.0", date: "2024-03-01", changes: [
        "• Apple Watch companion app with preview and chat. 💡 mikeful and others",
        "  • Preview updates at 1 FPS.",
        "  • Up to 10 chat messages. No emotes, not even as text if image on phone.",
    ]),
    Version(version: "0.183.0", date: "2024-02-26", changes: [
        "• Fix crash when streaming to https://github.com/sallar/mac-local-rtmp-server RTMP server. 🐛 JohannesLiv",
        "  • Adaptive bitrate will not work at all after about 4 GB of data sent. Requires server fix.",
        "• Ireland and tetris icons in store.",
        "• Updated korean translation. ✍️ 고블린",
        "• Fixed audio drift issue on iPhone 15?",
        "• Only show OBS remote control page in wizard when OBS is (likely) used. 🐛 JohannesLiv",
    ]),
    Version(version: "0.182.0", date: "2024-02-24", changes: [
        "• Make time widget text size same regardless of resolution.",
        "• Show error toast if an overlay (widget/filter) cannot be rendered.",
    ]),
    Version(version: "0.181.1", date: "2024-02-24", changes: [
        "• Keep screen on when showing remote control assistant. 🐛 djandrea.",
        "• Make capture device image size match session preset.",
        "  • Fixes draw on 720p stream on iPhone X.",
        "  • Might make image quality worse on some devices. Not sure.",
    ]),
    Version(version: "0.181.0", date: "2024-02-23", changes: [
        "• Less logging by default.",
        "• Major refactoring.",
        "• Show audio/video capture delta in debug overlay.",
        "• Fix SRT(LA) adaptive bitrate custom settings.",
        "  • Bitrate decrease speed was wrong. It used bitrate increase speed / 1000 as factor. Very wrong.",
    ]),
    Version(version: "0.180.1", date: "2024-02-22", changes: [
        "• Fix top and bottom parts of UI outside screen when using browser widget. 🐛 nn2p",
    ]),
    Version(version: "0.180.0", date: "2024-02-21", changes: [
        "• Experimental support for RTMP adaptive bitrate.",
        "  • Disabled by default. Enable in Settings → Streams → My stream → RTMP → Adaptive bitrate.",
        "• Trying to fix slowly declining bitrate again.",
        "  • Configure encoder bitrate to 10% higher for 10 seconds, then 0% higher, then 10% higher, and so on.",
    ]),
    Version(version: "0.179.0", date: "2024-02-18", changes: [
        "• Disable camera capture when remote control assistant is open. 💡 djandrea.",
        "  • Audio is still captured. Was not that easy to disable.",
        "• Make grid only cover video.",
        "• Fix adding widgets and buttons to scenes on iPad.",
        "• Top mic by default on iPad.",
        "• Fix tap screen to focus on iPad.",
        "• Try fixing slow bitrate drops after some time by periodically setting the bitrate. 🐛 all of us",
        "  • It is set every 10 seconds now, regardless if it changed or not.",
    ]),
    Version(version: "0.178.0", date: "2024-02-17", changes: [
        "• Fix phone screen (mirroring) glitches when switching scene.",
        "  • However, screen is black for a short while.",
        "• Show location shared counter in location information top right of UI.",
        "• Enable iPad and Mac (Designed for iPad) destinations. Force landscape on iPad. 🧑‍🏭 Spillmaker",
        "• Only allow pausing chat when in interactive chat mode. 🐛 ariathome, fonz",
    ]),
    Version(version: "0.177.0", date: "2024-02-15", changes: [
        "• Configurable location privacy regions. Your location will not be shared when in a privacy region.",
        "  • Settings → Location",
        "• Toggle in Settings → Location to enable location services.",
        "• Traditional chinese translation updated. ✍️ 一人HitoriGS",
        "• Configurable number of packets in flight in FastIRL algorithm.",
        "  • In my setup 200 is a bit low. The algorithm often decreases bitrate too much when switching camera.",
        "• Send more fake frames when switching camera for less gaps in video stream.",
        "• Toggle to enable/disable chat (and hide/show it). 💡 ariathome",
        "• Fix draw point on stream locally.",
    ]),
    Version(version: "0.176.0", date: "2024-02-13", changes: [
        "• Fix draw on stream when 16:9 video fills screen width but not height. 🐛 AdAstra",
        "• Fix lingering marker on RealtimeIRL map. 🐛 Rubaz",
        "  • Send explicit stop to server when ending stream.",
    ]),
    Version(version: "0.175.0", date: "2024-02-13", changes: [
        "• Configurable stream button color.",
        "  • Settings → Display → Stream button",
        "• Fix crash when entering high record and preset bitrates. 🐛 nn2p, adriportela95",
        "• Settings loading robustness.",
        "  • Makes it easier to install older versions to test with. However, unknown settings will either be replaced or discarded, so some settings may be lost! Always backup your settings before installing old versions of the app.",
        "• Replace pause chat with interactive chat in UI.",
    ]),
    Version(version: "0.174.0", date: "2024-02-11", changes: [
        "• Remove debug video preset setting.",
        "  • No one needs it, right?",
        "• Fix crash when muted and using remote control.",
    ]),
    Version(version: "0.173.0", date: "2024-02-08", changes: [
        "• German translation updated. ✍️ MaurisonX",
        "• Show disconnected icon next to disconnected cameras in scenes.",
        "• Fix video freeze if browser widget is incorrectly configured (too high resolution for example).",
        "• Polish translation updated. ✍️ Seebuch",
        "• Limit number of paused chat messages to 99, not to run out of memory.",
    ]),
    Version(version: "0.172.0", date: "2024-02-07", changes: [
        "• Quick button to hide local overlays. 💡 adriportela95",
        "• Spanish translation updated. ✍️ adriportela95",
        "• Show number of chat messages when chat is paused. 🧑‍🏭 NoFuture",
    ]),
    Version(version: "0.171.0", date: "2024-02-07", changes: [
        "• Select back, front, RTMP or external camera per scene.",
    ]),
    Version(version: "0.170.0", date: "2024-02-06", changes: [
        "• Bigger audio ring buffer (25 instead of 6 buffers, 1024 samples each).",
        "  • Not sure if it can fix some audio glitches.",
        "• Fix unwanted chat pause on iPad.",
        "• Fix browser widget scaling on iPad.",
        "• Select browser by default when creating a new widget.",
        "• iPad multitasking.",
        "  • Video now works in slide over view.",
    ]),
    Version(version: "0.169.0", date: "2024-02-04", changes: [
        "• Draw on stream styling.",
        "• Draw point (a small filled circle) on stream when tapping.",
        "• Major refactoring. Hopefully everything still works.",
    ]),
    Version(version: "0.168.0", date: "2024-02-04", changes: [
        "• Detect cameras plugged in after app starts.",
        "• Support for Cam Link 4K on iPad.",
        "  • For some reason the FPS is always 59.",
        "• Reload browser widgets using remote control assistant.",
        "• Refresh streamer status using remote control assistant.",
        "• Toggle to mirror front camera on stream.",
        "  • Rotate video in OBS for poor mans portrait streaming.",
        "  • Settings → Camera → Mirror front camera on stream",
    ]),
    Version(version: "0.167.0", date: "2024-02-03", changes: [
        "• Chat rework.",
        "  • Replace pause quick button with an interactive chat quick button.",
        "  • Pause chat when scrolling.",
        "• Fix bitrate overshoot when using flat bitrate in SRT(LA).",
    ]),
    Version(version: "0.166.0", date: "2024-02-02", changes: [
        "• Do not apply video effects multiple times when switching camera.",
        "• User defined LUTs.",
        "• Draw on stream undo button.",
    ]),
    Version(version: "0.165.0", date: "2024-02-01", changes: [
        "• Configurable maximum number of log lines (1-100k).",
        "• Configurable color spaces and LUT.",
        "  • In Settings → Camera.",
        "  • sRGB, P3 D65, HLG BT2020 and Apple Log.",
        "  • 3 bundled LUTs.",
        "    • It is not possible to upload your own LUTs yet.",
        "  • Known bug: LUTs are applied multiple times when switch camera giving weird image effects. This applies to other video effects as well.",
    ]),
    Version(version: "0.164.0", date: "2024-01-29", changes: [
        "• Make whole audio level bar red if clipping (above -1.0 dB).",
        "• Hide system overlays (long bar at bottom of screen) when showing black screen.",
        "• Experimental support for Bluetooth speaker and external non-Bluetooth mic (or built-in mic).",
        "  • Enable Settings → Debug → Audio → Bluetooth output only.",
        "• UI for Apple Log started. It does absolutely nothing!",
        "  • Press Camera quick button to see it.",
        "• Add support for 25 and 50 FPS.",
    ]),
    Version(version: "0.163.0", date: "2024-01-28", changes: [
        "• Slightly bigger quick button name font when using single column.",
        "• Draw on stream.",
        "  • Toggle draw mode with the draw quick button.",
    ]),
    Version(version: "0.162.0", date: "2024-01-28", changes: [
        "• Video effect picker rework.",
        "• Change mic using remote control.",
        "• Smaller styling changes.",
        "• Two columns in remote control assistant.",
        "• Remote control assistant receives log messages.",
        "  • Stores up to 100,000 entries, so many more than locally on the streamer's device.",
        "• Fix crash on iPhone 12 Mini when changing URL and pressing Done more than once?",
        "  • Changing the URL can sometimes make the UI unresponsive.",
        "  • Could probably happen on any device.",
        "• Log SRT overlay.",
    ]),
    Version(version: "0.161.0", date: "2024-01-27", changes: [
        "• Fix bad browser widget behavior after settings change.",
        "• Browser widget loading status in top right of UI.",
        "  • Disappears when at 100% for 5 seconds.",
    ]),
    Version(version: "0.160.0", date: "2024-01-27", changes: [
        "• Make settings layout picker nicer.",
        "• Show battery level and flame color in remote control assistant.",
        "• Filled recording button when recording.",
        "• Quick button to show recordings.",
        "• Time and triple widgets optimizations.",
        "• Remote control info in top right of UI and identified response message.",
        "  • Another non-backwards compatible change in the remote control protocol. Update to latest versions everywhere.",
    ]),
    Version(version: "0.159.0", date: "2024-01-26", changes: [
        "• Audio channels mapping.",
        "  • Settings → Debug → Audio.",
        "• New Custom IRL adaptive bitrate parameter ranges.",
    ]),
    Version(version: "0.158.0", date: "2024-01-26", changes: [
        "• Disable connection toggle.",
        "  • Settings → Streams → My stream → SRT(LA) → Connection priorities.",
        "• Browser widget performance improvements.",
        "  • For some reason the browser snapshots were 3 times bigger then expected. Dividing them by 3 greatly reduces power usage.",
        "  • Often uses GPU instead of CPU now.",
        "  • For some reason browsers behave badly after settings change. Out of sync and slow.",
    ]),
    Version(version: "0.157.0", date: "2024-01-25", changes: [
        "• OBS start and stop streaming confirmations.",
        "• Start/stop recording confirmations toggle.",
        "  • Settings → Display → Recording confirmations.",
        "• Show alert when settings are about to be reset on startup.",
        "• New remote control authentication. Not backwards compatible.",
        "  • Your remote control password will be lost.",
        "• Experimental global tone mapping toggle.",
        "  • Settings → Debug.",
        "• Default audio to speaker.",
        "  • Should make browser widget sound volume higher.",
        "  • Should use Bluetooth speaker if connected.",
        "• Tons of browser widget changes.",
        "  • Scale to fit video.",
        "  • Width and height are actually used as browser window size.",
        "  • FPS configuration.",
    ]),
    Version(version: "0.156.0", date: "2024-01-21", changes: [
        "• Make Settings → Display → Local overlays → Chat only hide/show the top left chat icon and info, not chat itself.",
        "• Three adaptive bitrate algorithms.",
        "  • Fast IRL - The default and battle tested algorithm",
        "  • Slow IRL - Same algorithm as Fast IRL, but changes bitrate slower.",
        "  • Custom URL - Same algorithm as Fast IRL, the the user configures various parameters.",
        "• Adaptive bitrate settings per stream.",
        "  • Less settings in Settings → Debug.",
        "• Remote control improvements.",
    ]),
    Version(version: "0.155.0", date: "2024-01-21", changes: [
        "• Remote control connect/disconnect toasts.",
        "• Audio only browser widgets.",
    ]),
    Version(version: "0.154.0", date: "2024-01-21", changes: [
        "• Initial support for browser widgets.",
        "  • Your phone will likely overheat and/or lag.",
        "  • Audio level is probably too low. Not sure how to increase it.",
        "  • Just as image widgets, browser widgets are mirrored on screen when front camera is used. No easy fix, unless not mirroring front camera on screen, which will make you confused because left and right are wrong.",
        "  • The browser content is often lower resolution than expected.",
        "  • Scaling of text may seem odd.",
        "  • They are only 5 FPS.",
        "  • And probably more quirks.",
    ]),
    Version(version: "0.153.0", date: "2024-01-20", changes: [
        "• Flashlight icon for torch.",
        "• Make front camera work after settings reset.",
        "• Remote control assistant can change scene, set zoom and change bitrate.",
        "• Change OBS cannot connect message.",
    ]),
    Version(version: "0.152.0", date: "2024-01-19", changes: [
        "• Default chat height set to 70% instead of 100% of screen.",
        "• Remote control that shows streamer's device status.",
        "  • Typically run Moblin on a Mac to see streamer's Moblin status.",
    ]),
    Version(version: "0.151.0", date: "2024-01-18", changes: [
        "• Fix RTMP Kick and Custom validation.",
    ]),
    Version(version: "0.150.0", date: "2024-01-17", changes: [
        "• OBS remote control styling.",
        "• Allow changing connection priorities when live.",
        "• Fix RTMP server crash on extended timestamp for type 3 chunks.",
        "• Spanish, German, Polish and Swedish translations updated.",
    ]),
    Version(version: "0.149.0", date: "2024-01-15", changes: [
        "• Machine translation to Italian.",
        "• Make custom RTMP(S) stream creation use H.264 video codec.",
        "• Use iOS color picker for chat colors.",
        "• Save SRT adaptive bitrate packets in flight config to disk.",
        "• Set maxbw to follow input bandwidth by default in SRT protocol.",
        "  • Seems to lower number of retransmissions with same video quality?",
        "• Enable adaptive bitrate by default for SRT(LA).",
        "  • Winging it.",
        "• Assign colors to all buttons to fix crash.",
    ]),
    Version(version: "0.148.0", date: "2024-01-14", changes: [
        "• Configurable SRTLA connection priorities.",
        "  • Often used to prioritize using one SIM card over another.",
        "  • Settings → Streams → My stream → SRT(LA) → Connection priorities.",
        "• OBS remote control audio sync.",
        "• Configurable global quick button colors.",
        "  • Configure per button in Settings → Display → Quick buttons.",
    ]),
    Version(version: "0.147.0", date: "2024-01-13", changes: [
        "• Upper case first letter in channel name by default.",
        "• URL keyboard for URL:s.",
        "• Spanish and Polish translations updated.",
        "• Game controller settings localized.",
        "• Replace OBS start/stop stream and OBS scene quick buttons with a OBS quick button.",
        "  • The new quick button opens a panel where you can start/stop stream, change scene, see source snapshot and source audio levels.",
        "  • Configure OBS scene name in Settings → My stream → OBS remote control for snapshot and audio levels.",
    ]),
    Version(version: "0.146.0", date: "2024-01-11", changes: [
        "• Only send location to RealtimeIRL when live.",
        "• Chinese (traditional) and German translations updated.",
        "• Show number of audio input channels in the UI next to the audio level meter.",
        "• Hide/show 3x3 alignment grid with quick button.",
        "• Do not show scroll bars for quick buttons and paused chat.",
    ]),
    Version(version: "0.145.0", date: "2024-01-11", changes: [
        "• Default location (GPS) settings.",
        "  • High precision.",
        "• Disable auto capitalization in many input fields.",
        "• Change OBS start/stop stream quick button icon to router(?) :slight_smile:",
        "  • The old icon will be used for a new stream switcher quick button.",
        "• Correctly duplicate various stream settings toggles.",
        "• Switch stream quick button.",
        "  • Immediately stops current live stream (if any), switches stream settings, and automatically goes live after 3 seconds.",
    ]),
    Version(version: "0.144.0", date: "2024-01-10", changes: [
        "• Less padding over Moblin icon and settings button.",
        "• Speed unit based on locale.",
        "  • Often km/h or mph.",
        "• More input checks in create stream wizard.",
        "  • Fixes OBS remote control crash when entering \"Ws://\" instead of \"ws://\".",
    ]),
    Version(version: "0.143.0", date: "2024-01-09", changes: [
        "• Show empty audio level bar on startup.",
        "  • Was sometimes full.",
        "• Optionally send your location to RealtimeIRL.",
        "  • The location service is turned off if no location is needed.",
        "  • Configured per stream.",
        "• Do not mirror external cameras.",
    ]),
    Version(version: "0.142.0", date: "2024-01-08", changes: [
        "• Remove duplicated camera entries in lists.",
        "• More logging of recording errors and when finished.",
        "• 4K video.",
    ]),
    Version(version: "0.138.0", date: "2024-01-07", changes: [
        "• Set target zoom level when zoom on camera switching in enabled.",
        "  • It was buggy, and now 300 ms latency hides most annoying frames.",
        "• Mirror external cameras immediately when received from capture.",
    ]),
    Version(version: "0.137.0", date: "2024-01-07", changes: [
        "• Remove all scene video effects except noise reduction.",
        "  • Since they are global now.",
        "• Optional FPS setting for RTMP server streams. Typically set to 30 for DJI drones.",
        "  • Set to 0 to use publisher FPS.",
        "• Fix mirroring when switching to/from RTMP server streams.",
        "• Fix showing wrong camera when switching from RTMP server stream to back camera.",
    ]),
    Version(version: "0.136.0", date: "2024-01-06", changes: [
        "• Fix quick buttons not fully shown after using keyboard when scroll is off.",
        "• No blackish frames when switching camera.",
        "  • Uses last frame from previous camera for 0.0-1.0 seconds after first frame from new camera. 0.3 seconds by default.",
        "    • Configure time in Settings → Debug → Video blackish.",
        "  • Looks like a frame of two are wrong sometimes. To be continued.",
        "• Recording page styling.",
        "• Game controller left and right buttons for Back and Front scenes by default.",
        "• Discover external cameras?",
    ]),
    Version(version: "0.135.0", date: "2024-01-06", changes: [
        "• Pixellate video effect widget.",
        "• Audio level for all(?) mics by default.",
        "• Game controller buttons text.",
        "• Global video effects.",
        "  • Not yet removed from scenes.",
        "• Keep game controller index when other controller is disconnected.",
        "• No audio drop out when switching camera (hopefully).",
        "• Show connect/disconnect game controller toast.",
    ]),
    Version(version: "0.134.0", date: "2024-01-05", changes: [
        "• Ramp to target zoom level when zoom on camera switching in enabled for less flickering.",
        "• Start/stop stream and start/stop recording with game controller.",
        "  • No confirmations though.",
        "• More information in \"Please enter your stream URL in stream settings before going live.\" toast.",
        "  • Preferably just use the wizard though.",
        "• Change scene with game controller.",
        "• Support for multiple game controllers.",
        "  • For more buttons, or if you are two persons",
    ]),
    Version(version: "0.133.0", date: "2024-01-03", changes: [
        "• Game controller with configurable buttons.",
    ]),
    Version(version: "0.132.0", date: "2024-01-03", changes: [
        "• SRT(LA) and RTMP(S) protocols part of create stream wizard's custom section.",
        "  • With separate fields for \"Stream id\" and \"Stream key\".",
        "• Korean translation updated.",
        "• Rename buttons to quick buttons.",
        "• Use a Bluetooth (or USB?) game controller to toggle mute (B) and torch (A).",
    ]),
    Version(version: "0.131.0", date: "2024-01-03", changes: [
        "• Do not show \"Low battery\" toast when charging.",
        "• Allow percent encoded SRT streamid (and other query parameter values).",
        "• Recording settings.",
        "  • Video codec, video bitrate and key frame interval.",
        "  • Resolution and FPS are same as stream.",
        "  • Found at Settings → Streams → My stream → Recording as resolution and FPS are per stream.",
        "• Show new recording settings per recorded video.",
        "• Charging bolt in black area (not half in video).",
        "• Make query and fragment in RTMP URL part of stream key and not tcUrl.",
    ]),
    Version(version: "0.130.0", date: "2024-01-02", changes: [
        "• Recording thumbnails.",
        "• Battery meter styling (fix non-precentage bar length).",
        "• Experimental mic per scene feature started.",
    ]),
    Version(version: "0.129.0", date: "2024-01-02", changes: [
        "• Spanish, German and Korean translations updated.",
        "• Record to disk.",
        "  • Uses stream settings (resolution, FPS and codec).",
    ]),
    Version(version: "0.128.0", date: "2024-01-01", changes: [
        "• RTMP server not experimental any more (but not perfect).",
        "• Turn off RTMP server when in background.",
        "  • Maybe revert this later.",
        "• Image settings button.",
        "  • Just exposure bias for now.",
        "• Remove subscriptions and add restore purchases button.",
    ]),
    Version(version: "0.127.0", date: "2024-01-01", changes: [
        "• Faster switching to RTMP server stream cameras.",
        "  • Do not flush buffers.",
        "• Only allow changing RTMP server settings when the server is disabled.",
        "  • Just to keep the code simple.",
    ]),
    Version(version: "0.126.0", date: "2024-01-01", changes: [
        "• Only show \"Low bitrate\" warning when connected.",
        "• Show charging icon when charging.",
        "• Show black frames when RTMP server streams are not connected.",
        "• Optionally vibrate when showing FFFFF, Low bitrate and Low battery toasts.",
        "  • Disabled by default. Enable is Settings → Display → Vibrate",
    ]),
    Version(version: "0.125.0", date: "2023-12-31", changes: [
        "• Widgets and buttons help text.",
        "• Bigger battery meter.",
        "• Show low battery warning toast every 10 seconds when below 5% left.",
        "• Show low bitrate warning toast every 15 seconds if below 500 kbps.",
        "  • Can be enabled/disabled in settings → Display.",
        "• RTMP server cameras can be streamed out from Moblin.",
        "  • Front camera frames are seen when no stream and when changing scene.",
    ]),
    Version(version: "0.124.0", date: "2023-12-30", changes: [
        "• Set exposure point of interest when tapping to focus.",
        "• Show interface name (en3, en4, ..) instead of Ethernet in SRTLA UI.",
        "• Configure human readable names for Ethernet network interfaces.",
        "  • Settings → Display → Network interface names",
        "• Move Chat and Audio level settings from Local overlays to Display.",
    ]),
    Version(version: "0.123.0", date: "2023-12-30", changes: [
        "• Show RTMP server icon in top right when enabled.",
        "  • RTMP server bitrate next to it when at least one client is connected.",
        "• Not forcing clock to 24h (as Americans insist on using 12h). :slight_smile:",
        "• RTMP server stability and major refactoring.",
    ]),
    Version(version: "0.122.0", date: "2023-12-29", changes: [
        "• RTMP server fixes. Can stream from IRL Pro to Moblin, but with wrong timestamps, so video all messed up.",
    ]),
    Version(version: "0.121.0", date: "2023-12-29", changes: [
        "• Select RTMP stream as camera for scenes.",
        "  • No longer an overlay.",
        "  • Does not work very well yet. Timing is off and possibly breaks audio.",
        "• Show toast when RTMP streams are connected and disconnected.",
        "• Fixed some bugs in RTMP server so IRL Pro at least can connect, but soon after disconnects.",
    ]),
    Version(version: "0.120.1", date: "2023-12-28", changes: [
        "• Remove times 3 on RTMP timestamp.",
    ]),
    Version(version: "0.120.0", date: "2023-12-28", changes: [
        "• Set default stream name to selected platform name in create stream wizard.",
        "• Add heart and looking icons to store.",
        "• RTMP server settings restructure and more clarifications.",
        "• Rename RTMP app from `camera` to `live`.",
        "  • So now it is `rtmp://<my-ip-address>:1935/live/foobar`.",
    ]),
    Version(version: "0.119.0", date: "2023-12-28", changes: [
        "• Experimental RTMP server settings.",
        "• Multiple parallel RTMP streams with different stream keys.",
        "• Kick chatroom example in wizard.",
    ]),
    Version(version: "0.118.0", date: "2023-12-27", changes: [
        "• RTMP server can show video on stream in fixed location and same resolution as received over RTMP.",
        "  • Only tested with ffmpeg. I'm sure it does not work with all RTMP publishers.",
        "  • Works best if RTMP FPS matches stream FPS.",
        "• Support for B-frames in RTMP server.",
        "• Add and remove RTMP overlay when client connects and disconnects.",
        "• German translations updated.",
    ]),
    Version(version: "0.117.0", date: "2023-12-26", changes: [
        "• Move \"Tap screen to focus\" from Display to Camera settings page.",
        "• Date in version history.",
        "• Korean translation updated.",
        "• RTMP server implementation started. Far from complete, but a client can connect.",
        "  • Received audio is discarded. Received video is also discarded, but logged.",
    ]),
    Version(version: "0.116.0", date: "2023-12-25", changes: [
        "• German translation updated.",
        "• Remove \"😎 Going live at <stream> 😎\" and \"🤞 Connecting to <stream> 🤞\" as they don't add much value over just the failure toasts. They are often just seen a fraction of a second, which is just irritating.",
        "• Improved OBS remote control disconnection handling. Update start/stop stream button state after reconnect.",
        "• Screenshot in OBS remote control wizard.",
        "• Only show error toast when listing OBS scenes when OBS remote control is configured but not connected.",
    ]),
    Version(version: "0.115.0", date: "2023-12-25", changes: [
        "• Fix OBS remote control edge case in Create stream wizard.",
        "• Battery percentage enabled by default.",
        "• Show error toast when pressing OBS scene button with OBS remote control is not configured.",
        "• \"Setup\" button instead of \"Go live\" when no stream is configured.",
        "  • The \"Setup\" button opens the \"Create stream wizard\" when pressed.",
        "• Only show viewers, chat statistics and OBS status in top left in UI if configured.",
        "• Visual indicator for widgets that have configurable position and/or size.",
        "• Translations continued (mostly auto translated, to be improved).",
    ]),
    Version(version: "0.114.0", date: "2023-12-24", changes: [
        "• Added \"Chat messages\" to stream summary.",
        "• Snow behind black screen.",
        "• Always use create stream wizard.",
        "• Added scuffed YouTube and AfreecaTV create stream wizards.",
        "• Setup OBS remote control as part of create stream wizard.",
    ]),
    Version(version: "0.113.0", date: "2023-12-24", changes: [
        "• Let it snow on screen.",
        "  • Enable in Settings → Debug → Let it snow.",
    ]),
    Version(version: "0.112.0", date: "2023-12-24", changes: [
        "• Shorter disconnected and failed to connect error messages.",
        "• Create stream wizard continued.",
        "• Increased default bitrate from 3 Mbps to 5 Mbps.",
        "• Only show SRT(LA) settings when SRT(LA) is configured in URL.",
        "• Message in OBS remote control toasts.",
        "• Add failure toast if start/stop OBS stream fails.",
        "• Show bad URL error message after input field instead of as a toast.",
    ]),
    Version(version: "0.111.0", date: "2023-12-23", changes: [
        "• Rework connection toasts.",
        "  • Show FFFFF if disconnected.",
        "  • Show Failed to connect if no connection could be established.",
        "  • Increase initial reconnect timer to 7 seconds (from 5). It gets higher over time, up to 60 seconds.",
        "• Average and highest bitrate in stream summary statistics.",
    ]),
    Version(version: "0.110.0", date: "2023-12-23", changes: [
        "• Confirm dialog when pressing OBS start/stop stream button.",
        "• Move Local overlays, Tap screen to focus, Battery percentage and Quick buttons to Display settings.",
        "• Move Back camera, Front camera, Zoom, Bitrate presets and Video stabilization to Camera settings.",
        "• Only show bitrate and uptime local overlays in top right when live.",
        "• Global buttons. Only widget buttons are per scene now. The rest are always visible (if enabled in Settings → Display → Quick buttons).",
        "  • This makes new buttons appear automatically when upgrading.",
        "• Highest thermal state in streaming history.",
        "• Lowest battery percentage in streaming history.",
        "• Create stream wizard continued.",
        "• Record UI started. Behind experimental toggle. Does not save audio and video to file yet.",
        "• Version history (changelog) in Settings → About → Version history.",
        "• Rename Quick buttons to Buttons.",
    ]),
    Version(version: "0.109.0", date: "2023-12-21", changes: [
        "• B-frames toggle.",
        "• Fix total bytes for RTMP streams in streaming history.",
    ]),
    Version(version: "0.108.0", date: "2023-12-21", changes: [
        "• Create stream wizard continued.",
        "• Fixed swapped H.264 and H.265 in local overlay.",
        "• Streaming history with some basic information.",
        "• Fix \"dropped frames\" when streaming RTMP(S) directly to Twitch, Kick and YouTube.",
        "  • Disabling frame reordering (aka B-frames) makes it work. Has been broken since 0.5.0 😄",
    ]),
    Version(version: "0.107.0", date: "2023-12-20", changes: [
        "• Unfinished \"create stream wizard\" behind experimental toggle.",
        "  • Enable wizard with Settings → Debug → Create stream wizard.",
        "• Show announcements when using Twitch chat.",
        "• 128 Kbps audio bitrate by default.",
        "• Slightly more compact stream info in UI.",
        "• Slider to configure audio bitrate.",
    ]),
    Version(version: "0.106.0", date: "2023-12-18", changes: [
        "• iOS 16.4",
        "• Support for any number of Ethernet connections in SRTLA (not yet confirmed that it works).",
        "  • Still max one WiFi and one Cellular.",
    ]),
    Version(version: "0.105.0", date: "2023-12-17", changes: [
        "• Require iOS 17.2 or higher.",
        "  • The plan is to support iOS 16.4 as well.",
        "• Find external cameras.",
        "  • I only get it working on Mac 😦",
    ]),
    Version(version: "0.104.0", date: "2023-12-17", changes: [
        "• Fix camera selection when running the iOS app on macOS.",
    ]),
    Version(version: "0.102.0", date: "2023-12-17", changes: [
        "• Quick button settings.",
        "  • Toggle to enable and disable scroll.",
        "  • Toggle to show button names.",
        "  • Toggle to show one or two columns.",
        "    • The buttons are slightly larger when using one column.",
        "• More translations updates.",
        "• Toggles to enable/disable BTTV, FFZ and 7TV emotes.",
        "  • Settings → Streams → My Stream → Chat",
    ]),
    Version(version: "0.101.0", date: "2023-12-16", changes: [
        "• Allow audio bitrate up to 320 kbps. Device dependent what the actual limit is.",
        "  • Will show your configured bitrate in UI. Might be lower in audio encoder (probably 192 kbps).",
    ]),
    Version(version: "0.100.0", date: "2023-12-15", changes: [
        "• Make audio bitrate configurable. 32 • 192 kbps (AAC). 64 kbps by default. Should probably be increased later on.",
        "  • I have not tested if the quality is better with higher bitrate. But it should be 🙂",
    ]),
    Version(version: "0.99.1", date: "2023-12-15", changes: [
        "• Fix screen video sometimes mirrored.",
    ]),
    Version(version: "0.99.0", date: "2023-12-15", changes: [
        "• Support for Twitch chat /me, optionally in username color.",
        "• Fix camera names when running on macOS.",
        "• Google translated strings in some places. To be improved, for sure! 🙂",
    ]),
    Version(version: "0.98.0", date: "2023-12-14", changes: [
        "• Spanish, German and French translation updated.",
        "• Toggles to enable/disable Twitch, Kick, YouTube, AfreecaTV and OBS remote control.",
    ]),
    Version(version: "0.97.0", date: "2023-12-14", changes: [
        "• Default zoom presets based on iPhone model.",
        "• Allow settings OBS websocket URL to empty string.",
    ]),
    Version(version: "0.96.1", date: "2023-12-13", changes: [
        "• Fix OBS websocket error \"The resource could not be loaded because the App Transport Security policy requires the use of a secure connection\" by allowing non-secure connections.",
    ]),
    Version(version: "0.96.0", date: "2023-12-12", changes: [
        "• Show OBS WebSocket password as stars.",
        "• Rename back cameras to make them easier to understand.",
        "• Fewer bitrate presets by default (1, 3, 5 and 7 Mbps).",
        "• Updated German and French translations.",
    ]),
    Version(version: "0.95.2", date: "2023-12-12", changes: [
        "• Show OBS scenes in the same order as in OBS.",
    ]),
    Version(version: "0.95.1", date: "2023-12-12", changes: [
        "• Fix OBS websocket crash when entering an invalid URL.",
    ]),
    Version(version: "0.95.0", date: "2023-12-11", changes: [
        "• Start/stop OBS stream button (using OBS websocket/remote control).",
        "• Change default stream settings to 1080p, H.265 and srt://my_public_ip:4000. Rename default stream from Twitch to Main.",
        "• Show toast explaining that the stream URL has to be configured before going live.",
        "• Show OBS websocket connection error message in UI (top left).",
    ]),
    Version(version: "0.94.0", date: "2023-12-10", changes: [
        "• OBS Websocket settings in deep link.",
        "  • See https://github.com/eerimoq/moblin#import-settings-using-moblin-custom-url for details.",
        "• Optionally show current OBS scene, streaming state and recording state in top left of UI.",
        "• \"All icons\" subscription (monthly and yearly).",
    ]),
    Version(version: "0.93.0", date: "2023-12-09", changes: [
        "• More icons in store.",
        "• Translations update.",
        "• Black screen button.",
        "• Use new screen rendering again (as it saves energy), at least for now.",
        "• Fix out of sync mirroring when swapping camera.",
        "• Change OBS scene on server.",
    ]),
    Version(version: "0.92.0", date: "2023-12-08", changes: [
        "• Allow non-lowercased scheme and spaces in stream URL.",
        "  • Automatically convert scheme to lower case and remove spaces.",
        "• Always show the whole URL. Use multiple lines if needed.",
        "• Move back to using metal screen rendering to find out if it fixes screen lag problem.",
        "  • It uses more CPU, so will make phone warmer. Hopefully ok.",
    ]),
    Version(version: "0.91.0", date: "2023-12-07", changes: [
        "• Updated translations.",
        "• Updated usage strings for App Store.",
    ]),
    Version(version: "0.90.0", date: "2023-12-06", changes: [
        "• Camera and microphone usage descriptions (requested by App Store review).",
    ]),
    Version(version: "0.89.0", date: "2023-12-06", changes: [
        "• Reorder scenes to your liking.",
        "• Duplicate scene button when swiping left.",
        "• Duplicate stream button when swiping left.",
        "• Korean translation started.",
        "• Fix empty string translation in German.",
    ]),
    Version(version: "0.88.0", date: "2023-12-05", changes: [
        "• Fix wrong zoom factor limits on telephoto camera.",
        "• Updated French, German and Polish translations.",
    ]),
    Version(version: "0.87.0", date: "2023-12-04", changes: [
        "• German translation.",
        "• More icons.",
    ]),
    Version(version: "0.86.0", date: "2023-12-03", changes: [
        "• Fix upside-down video when starting app in landscape right.",
    ]),
    Version(version: "0.85.0", date: "2023-12-02", changes: [
        "• Zoom speed setting.",
        "• Add dual wide camera to list of back cameras.",
        "• Optionally show selected (back) camera in top left of UI.",
        "• Only show zoom presets that are relevant for current lens and camera.",
        "• Fix zoom limits for all lenses.",
        "  • Known bug: Telephoto camera is hard coded to 5x. So only works correctly for 15 Pro Max.",
        "• Initial support for AfreecaTV chat.",
        "• Remove buggy bloom filter. It didn't work and I'm sure nobody uses it, right? 🙂",
        "• Polish, Chinese (Simplified) and French translations.",
        "• Try to fix occasionally lagging screen (by always displaying frames immediately).",
    ]),
    Version(version: "0.84.0", date: "2023-11-29", changes: [
        "• Debug log number of audio channels and samples every 10 seconds.",
        "• Refactor SRT(LA) remote connection handler. Mainly affects reconnect logic.",
        "• Initial support for Spanish and Swedish. Not finalized, so not all strings are translated.",
        "  • Feel free to help out translating to your language.",
    ]),
    Version(version: "0.82.0", date: "2023-11-26", changes: [
        "• Røde audio level debug.",
        "  • Enable Settings → Debug → Audio → Røde audio level and audio level should show in top right of UI.",
        "  • When enabled, audio level is based on first channel. Other channels are ignored.",
    ]),
    Version(version: "0.81.0", date: "2023-11-26", changes: [
        "• More optimizations for less power usage.",
        "  • Quite big changes. Might break something.",
        "• Fix muted not showing in UI.",
        "• Reorder settings.",
    ]),
    Version(version: "0.80.0", date: "2023-11-25", changes: [
        "• Key frame interval settings. 2 by default (as it was before).",
        "  • Settings → Streams → Stream → Video → Key frame interval",
        "  • Usually 2 is good. Higher means potentially higher video quality for same bitrate. Lower means faster recovery from frame drops.",
        "• Update chat in UI every 200 ms instead of immediately on every message.",
        "  • Not to flood UI update engine when lots of messages are received.",
        "• Back and front camera selection (triple, dual, ultra wide, wide and telephoto).",
        "  • Zoom works, but factor is a bit off I think.",
        "  • Settings → Back camera",
        "  • Settings → Front camera",
    ]),
    Version(version: "0.79.0", date: "2023-11-23", changes: [
        "• A few optimizations that lowers CPU usage a little.",
        "  • Audio level meter only updates if dB changes more than 5 dB. Maybe lower the threshold a little later on.",
    ]),
    Version(version: "0.78.0", date: "2023-11-20", changes: [
        "• Automatically navigate back from picker views on selection change.",
        "• Revert always using multi camera capture session as 720p does not work with it.",
    ]),
    Version(version: "0.77.0", date: "2023-11-19", changes: [
        "• Fix RTMP crash when going live second time.",
    ]),
    Version(version: "0.76.0", date: "2023-11-19", changes: [
        "• Replace \"Some settings are disabled when Live\" alert with similar information on first settings page.",
        "• Time widget background.",
        "• Preparations for Picture in Picture.",
        "  • Reworked scene settings camera selection.",
        "  • Using multi camera capture session instead of single camera capture session. Will hopefully work on phones that do not support multi camera capture.",
        "• Major refactoring in streaming code. Hopefully no functional change.",
    ]),
    Version(version: "0.75.0", date: "2023-11-18", changes: [
        "• Optionally configure SRT overhead bandwidth. Mostly for testing things in first release.",
        "• Some logging of SRTLA trying to reconnect when it shouldn't.",
        "• A few small optimizations to use less energy.",
        "  • Saves a few percent CPU when the scene has no widgets.",
    ]),
    Version(version: "0.74.0", date: "2023-11-17", changes: [
        "• All haishinkit logging as debug.",
        "• Adaptive bitrate cracking audio after low bitrate fix (hopefully) when streaming to OBS.",
        "  • Bitrate will settle for about 80% of target bitrate. Under investigation.",
        "  • New algorithm will not change resolution to achieve low bitrate, but always set dataRateLimits instead.",
    ]),
    Version(version: "0.73.0", date: "2023-11-14", changes: [
        "• \"Designed by\" list.",
        "  • Just let me know if you want be added to the list, and I'll consider it 🤔",
        "• Higher allowed exposure duration (integration time).",
        "• Exposure bias debug setting.",
        "• Fix duplicated Kick chat messages.",
        "• Fix video freeze when using RTMP and entering/exiting background.",
        "  • Probably not fully fixed.",
        "• Fix duplicated twitch viewers connection.",
        "• Adjusted adaptive bitrate algorithm.",
        "• Quickly reconnect chat and viewers after entering foreground.",
        "• Selected builtin mic saved.",
        "• Added cinematic image stabilization (in addition to off and standard).",
        "• Replace debug toggle with log level picker and SRT overlay toggle.",
        "  • Save the two settings to disk.",
    ]),
    Version(version: "0.72.0", date: "2023-11-11", changes: [
        "• Return to previous settings page automatically when done editing text field.",
        "  • For easier settings navigation.",
        "• Save text fields when pressing back, if modified.",
        "  • Less error prone.",
        "• Same close button style in mic and bitrate quick settings as main settings.",
        "• Warning message if chat is hidden (just like for paused).",
        "• Do not change scene when moving widgets.",
        "• Select chat font size with slider.",
    ]),
    Version(version: "0.71.0", date: "2023-11-10", changes: [
        "• Configurable maximum chat message age in seconds. Disabled by default.",
        "• Kick chat emotes.",
        "• Bigger settings close button \"hit area\"?",
        "• Settings close button alignment.",
    ]),
    Version(version: "0.70.0", date: "2023-11-09", changes: [
        "• Disable some settings when Live.",
        "  • To not accidentally stop stream.",
        "• Always show layout picker and close button when in settings.",
    ]),
    Version(version: "0.69.0", date: "2023-11-08", changes: [
        "• Rework settings layout for more feedback when configuring for example chat.",
        "  • Remove stream preview.",
        "  • Show settings on left half, right half or full screen. Stream visible other half.",
        "• Experimental YouTube chat.",
        "  • Requires Google API Key and Video Id as input.",
        "    • See https://console.cloud.google.com/. Create an API Key and enable \"YouTube Data API v3\".",
        "    • See https://www.youtube.com/watch?v=<videoId> for Video Id.",
        "• Goblina icon (future Moblina?)",
    ]),
    Version(version: "0.68.0", date: "2023-11-07", changes: [
        "• Configurable chat height in percent of screen height (roughly).",
        "• Configurable chat width in percent of screen width (roughly).",
        "• Show \"Chat is paused\" warning message when chat is paused.",
    ]),
    Version(version: "0.67.0", date: "2023-11-06", changes: [
        "• Show chat stats in top left, above viewers.",
        "• Always show entire last chat message.",
        "  • Before this fix last message was often cut in half when screen was full of (long) messages.",
        "• Pause chat button.",
        "  • Can scroll chat while paused.",
        "  • Max 50 messages.",
        "  • Automatically scrolls to bottom when unpaused.",
        "  • Messages after red horizontal line were received while paused.",
        "  • Zoom and scene buttons cannot be pressed with paused chat.",
        "    • Should probably hide them for clarity later on.",
    ]),
    Version(version: "0.66.0", date: "2023-11-05", changes: [
        "• Make control bar wider if Accessibility Button Shapes is enabled.",
        "• Nicer button alignment.",
        "• Optionally use generated square wave as audio source instead of mic for debugging (or really scuffed streams).",
        "• Optional battery percentage.",
        "• Chat statistics redesign with automatic unit (second or minute) and total message count.",
        "• Smoother (moving average) bitrate in UI when using SRT(LA).",
        "  • Mainly because key frames makes jump up and down every second.",
    ]),
    Version(version: "0.65.0", date: "2023-11-04", changes: [
        "• New SRT(LA) adaptive bitrate algorithm, by Rick. Behind toggle.",
        "  • Use SRT delay of 2000 ms, not lower.",
        "  • Lowers resolution to 16x9 when connection is bad.",
        "• Rename deep link URL scheme from mobs:// to moblin://, and fix it!",
        "• Workaround for crash when another app uses audio at the same time.",
        "  • Audio level in UI will say Unknown in this case.",
        "  • If audio freezes, change to another stream setting and back should fix it.",
    ]),
    Version(version: "0.64.0", date: "2023-11-02", changes: [
        "• Rename app to Moblin.",
        "• Use new 7TV emotes API.",
        "  • Old stopped working completely.",
    ]),
    Version(version: "0.63.0", date: "2023-11-02", changes: [
        "• Better support for Larger Text (Display Zoom in iOS settings).",
        "• Better support for Accessibility Button Shapes.",
        "• Slash over hide chat button icon.",
    ]),
    Version(version: "0.62.0", date: "2023-10-31", changes: [
        "• Use external mic if available when starting app.",
        "• Do not close mic selection view when plugging external mic in and out.",
    ]),
    Version(version: "0.61.0", date: "2023-10-30", changes: [
        "• Show long Kick chat messages on same line as username.",
        "• Maximum number of buttons based on text size and zoom.",
        "• Automatically use external mic when plugged in. Fall back to most recently used internal mic when unplugged. (I know, it kinda worked already, but now official.)",
        "  • Builtin front mic always used by default currently.",
        "• Update mic text in top left and mic selection menu on mic change.",
    ]),
    Version(version: "0.60.1", date: "2023-10-30", changes: [
        "• Fix SRT periodically reconnecting bug introduced in 0.60.0.",
    ]),
    Version(version: "0.60.0", date: "2023-10-29", changes: [
        "• Prettier chat message line wrapping.",
        "• Chat message shadow replaced by border.",
        "  • Fairly CPU intensive for busy chats.",
        "• External mic. Only tested with bluetooth headset.",
        "  • No auto selection.",
        "  • Just as before, changing mic interrutps audio and video stream for a short time. To be fixed later.",
        "• Disable purchase button and show spinner until purchase completed.",
        "• SRTLA now automatically adds connections when available. For example when connecting to WiFi.",
        "  • No timers worked since move to non-main thread long time ago. Big problem!",
    ]),
    Version(version: "0.59.0", date: "2023-10-28", changes: [
        "• Fix animated chat emotes.",
        "• Fix chat Twitch chat emotes when long (more than one Unicode point) emojis in message before the Twitch emote.",
        "• Display number of viewers as 12, 118, 1,5K, 10K, 1,2M(?) and similar.",
        "• Queen icon.",
        "• Optional chat message timestamp.",
    ]),
    Version(version: "0.58.0", date: "2023-10-27", changes: [
        "• Re-add full screen settings button of first page.",
        "• New settings maximize and minimize icons.",
        "• Show sensitive text as stars.",
        "• Fix chat sometimes showing as disconnected when connected.",
        "• Improved input validation for twitch chat emotes.",
        "• Get In-App Purchases from App Store (only \"King\" icon).",
        "  • Hopefully this does not impact TestFlight negatively.",
        "  • All icons are free in TestFlight.",
    ]),
    Version(version: "0.57.0", date: "2023-10-26", changes: [
        "• Big SRT packet toggle. Mainly for debugging.",
        "  • Big packets means 7 MPEG-TS packets per SRT packet, 6 otherwise.",
        "• Animated emotes off by default as they are fairly CPU intensive.",
        "• Fixed text editing flickering and copy-paste bug.",
        "  • Now Enter must be pressed to submit text field changes.",
        "  • Had to remove button for full screen settings. Can hopefully re-add it later.",
    ]),
    Version(version: "0.56.0", date: "2023-10-25", changes: [
        "• Button to toggle hide/show chat.",
        "• Slightly better logging and error messages.",
        "• Fix hang when changing stream quickly.",
        "• Remove lots of settings migrations (should not affect users).",
        "• Make paste in URL text field work again. (Or at least better, still not perfect)",
    ]),
    Version(version: "0.55.0", date: "2023-10-24", changes: [
        "• Fix URL cursor jumping around bug.",
        "• Try to fetch emotes again after 30+ seconds on failure.",
        "• Slight performance improvements.",
        "• Bump SRT library to version 1.5.3.",
    ]),
    Version(version: "0.54.0", date: "2023-10-23", changes: [
        "• Emotes are always cached locally for fewer network requests and faster loading.",
        "• Global emotes in Kick chat.",
        "• Redesign chat settings.",
        "• Workaround to make https://github.com/irlserver/irl-srt-server work.",
        "• Show toast if emotes could not be fetched.",
        "• Red chat icon if not connected or emotes failed to load.",
    ]),
    Version(version: "0.53.0", date: "2023-10-22", changes: [
        "• BTTV, FFZ and 7TV emotes. Only for Twitch chat. Kick chat later on.",
        "  • Only cached when animated. To be improved.",
        "  • Optionally animated.",
        "    • Settings → Local overlays → Chat → Animated emotes",
        "  • Sometimes 7TV emotes are not received from server. Unknown why.",
        "• Fix \"Muted\" font color in light mode.",
        "• Separate bold toggles for username and message.",
    ]),
    Version(version: "0.52.0", date: "2023-10-21", changes: [
        "• Twitch emotes in chat.",
        "  • Messages with emotes that are longer than the screen is wide are weirdly formatted.",
    ]),
    Version(version: "0.51.0", date: "2023-10-21", changes: [
        "• Display chat username in color received from Twitch, if available.",
        "• Manual focus point when phone is rotated 180 degrees now works.",
        "• Remove manual focus point if rotating the phone more than 10 degrees in any direction.",
        "  • Remove auto focus toast.",
        "  • Will be hard to use manual focus when in a moving vehicle.",
        "• Move adaptive bitrate toggle from Video to SRT(LA) page.",
        "• Colorful audio level meter that updates with 5 Hz.",
    ]),
    Version(version: "0.50.0", date: "2023-10-20", changes: [
        "• Configurable chat font size. Increased to 17 (from 13) by default.",
        "  • Settings → Local overlays → Chat → Font size",
        "• Total chat redesign with lots of configuration possibilities. Please let me know if you want the old chat design back.",
        "  • Username and message colors.",
        "  • Optionally bold text.",
        "  • Optional background.",
        "  • Optional text shadow.",
    ]),
    Version(version: "0.49.0", date: "2023-10-20", changes: [
        "• Fix SRT and SRTLA URL parameters bug. Now srt://foo.com:1234?latency=2000 works.",
        "• SRT and SRTLA latency setting in milliseconds in UI. Any latency parameter given in the URL overrides this setting.",
        "  • Settings → Streams → Stream → SRT & SRTLA → Latency",
        "• Support for both left and right landscape orientation. Video always with gravity down (never upside down).",
        "• Audio level as bar or number. Color thresholds are set to -8 dB (red) and -18 dB (yellow). One bar is -60 dB.",
        "  • Bar colors to be added. Currently icon changes color.",
    ]),
    Version(version: "0.48.0", date: "2023-10-19", changes: [
        "• Fix light mode in settings.",
    ]),
    Version(version: "0.47.0", date: "2023-10-19", changes: [
        "• Change preview to selected scene when in settings.",
        "• Rework settings buttons in top right. Should be easier to press now.",
    ]),
    Version(version: "0.46.0", date: "2023-10-18", changes: [
        "• Various minor UI tweaks.",
        "• Major UI rework. Introducing a split view where settings and video are displayed at the same time. Makes it easier to see setting changes and especially easier scene setup.",
        "  • Video on screen becomes black if quickly opening and closing settings. Unknown why. Just press slower and it seems to work.",
        "  • Previewed scene cannot be changed from settings. Select the scene you want to see before opening settings.",
    ]),
    Version(version: "0.45.0", date: "2023-10-17", changes: [
        "• Button icon filter styling.",
        "• Fix crash when going live with SRT stream URL with query parameter without value, for example srt://foo.com?streamid.",
    ]),
    Version(version: "0.44.0", date: "2023-10-17", changes: [
        "• Swapping between SRT streams works now. Video do not freeze anymore.",
        "• Configure video stabilization as Off or Standard at Settings → Video stabilization.",
        "• Replace debug log copy and clear text buttons with images. Share link instead of copy to clipboard.",
    ]),
    Version(version: "0.43.0", date: "2023-10-16", changes: [
        "• White battery and thermal level indicators when all good.",
        "• Fix settings page getting stuck in landscape mode. I hope...",
        "• Zoom and scene pickers styling (fix bottom padding).",
        "• Fix invisible button icon picker in light mode.",
    ]),
    Version(version: "0.42.0", date: "2023-10-15", changes: [
        "• Icon (three horizontal lines) on list items that can be moved.",
        "• Input bitrate presets in Mbps instead on bits.",
        "• Make battery indicator border white.",
        "• Button icon selection in filtered grid view.",
        "• Import/export as JSON blob instead of base64 encoded JSON blob.",
        "• Store bitrate preset settings to disk on move, delete and create.",
    ]),
    Version(version: "0.41.0", date: "2023-10-15", changes: [
        "• Time widget, showing local time as HH:MM:SS. For example 14:44:10. Hard coded font and size. To be continued.",
        "• Split local overlays settings page in sections.",
        "• More icons.",
        "• Redesigned battery indicator.",
        "• Optionally set X zoom (rename to default zoom?) when switching to a camera.",
        "• Maximum screen FPS setting.",
        "• Change icon on home screen when changing icon in app.",
        "• Default widget position and size based on widget type.",
        "  • Time widget in top right.",
        "  • Image and browser not covering whole screen.",
    ]),
    Version(version: "0.40.0", date: "2023-10-14", changes: [
        "• Make icon selection survive app restart.",
        "• Show manual focus point as yellow box.",
        "• Show store closed alert when trying to buy icon.",
        "• Always auto focus after camera swap.",
    ]),
    Version(version: "0.39.0", date: "2023-10-13", changes: [
        "• Logging of available mics.",
        "• Create streams using mobs:// custom URL.",
        "  • See https://github.com/eerimoq/mobs/tree/main#import-settings-using-mobs-custom-url for details.",
        "• Icon cosmetics. Can select plain or Halloween icon. Showcase more icons. Selection is currently reset at app start. And btw, I designed them, so they are not that pretty. 🙂",
    ]),
    Version(version: "0.38.0", date: "2023-10-13", changes: [
        "• Configurable bitrate presets.",
    ]),
    Version(version: "0.37.0", date: "2023-10-11", changes: [
        "• Tap screen to focus feature off by default.",
        "• Set focus point to center of screen when returning to auto focus mode.",
    ]),
    Version(version: "0.36.0", date: "2023-10-11", changes: [
        "• Super simple (and probably bad) adaptive bitrate algorithm for SRT(LA). Big work in progress.",
        "  • Enabled with Settings → Streams → Stream → Video → Adaptive bitrate.",
        "• SRT debug overlay. ",
        "  • Enabled with Settings → Debug → Debug.",
        "• Fix tap screen to focus. Double tap to use auto focus again.",
    ]),
    Version(version: "0.35.0", date: "2023-10-10", changes: [
        "• Tap screen to focus.",
        "• Setting to enable/disable \"Tap screen to focus\".",
    ]),
    Version(version: "0.34.0", date: "2023-10-09", changes: [
        "• Current zoom level as local overlay.",
        "• Improved stream URL help. Added Facebook and YouTube examples.",
    ]),
    Version(version: "0.33.0", date: "2023-10-08", changes: [
        "• Pinch to zoom (in addition to zoom presets).",
        "• More intuitive back camera zoom preset levels. That is, level 0.5 is now 0.5x. In previous releases 1.0 was 0.5x, which was not very intuitive.",
    ]),
    Version(version: "0.32.0", date: "2023-10-08", changes: [
        "• Transparent browser widget background.",
        "• Rename microphone to mic.",
        "• Show toast when changing bitrate and mic.",
        "• Apply video mirroring after camera selection for smoother experience.",
        "• Changing mic after app has been in background now works.",
        "• No special audio and video handling when entering and exiting background. Seems to make the app more robust.",
        "• Remove width, height and custom CSS from browser widget settings for now. They were not used anyway.",
        "• Bitrate and mic quick settings displayed on half landscape screen.",
    ]),
    Version(version: "0.31.0", date: "2023-10-07", changes: [
        "• Rename web page to browser (same as OBS).",
        "• Button to select Front, Back or Bottom builtin microphone. You must create the button yourself if you are upgrading from an older MOBS version (Settings → Scenes → Buttons and then Settings → Scenes → My scene → Add button). Clean installations will get the button by default.",
        "• Front microphone selected by default.",
        "• Show selected microphone in top-left of UI.",
        "• Browser widget fixes. Still very buggy.",
    ]),
    Version(version: "0.30.0", date: "2023-10-06", changes: [
        "• Dedicated scene camera selection instead of a camera widget. Mostly to simplify implementation. Might be a widget again in the future. Also preparation for picture in picture.",
        "• More widget icons.",
        "• Rename close buttons to cancel in add and create popovers.",
        "• Initial support for web page widgets. Has barely been tested. You probably have to create and configure the widget, and then restart mobs for it to work. They are only updated with 5 Hz, so not very smooth.",
    ]),
    Version(version: "0.29.0", date: "2023-10-05", changes: [
        "• Mirror front camera on iPhone screen. Do not mirror live stream. Unfortunately the mirror effect is applied faster than the camera change, so it looks a bit odd on screen when changing camera. The stream is not affected by this glitch.",
        "• Higher audio volume.",
    ]),
    Version(version: "0.28.0", date: "2023-10-05", changes: [
        "• Weird workaround to make my Android WiFi hotspot work. Had to ignore an error that shouldn't occur.",
        "• Support for multiple video effects of same kind. (I did cheat a lot before by creating video effects at startup.)",
        "• Fix so torch is not turned off when pressing buttons, or other action that changes the scene.",
    ]),
    Version(version: "0.27.0", date: "2023-10-04", changes: [
        "• Zoom settings.",
        "• More debug logging of SRTLA connections. (Ethernet remained with 2% of uploads after unplugged.)",
        "• Settings storage rework that hopefully does not affect anyone. Should only affect users that upgrade from a really old version.",
    ]),
    Version(version: "0.26.0", date: "2023-10-03", changes: [
        "• Experimental: Try to use all camera lenses. Did not work on my iPhone X, but I think it will work on newer models. The selected mode can be found in the debug log. For example \"Dual camera\" with its zoom and physical cameras.",
        "• Experimental: 0.5x back camera zoom.",
        "• SRTLA statistics with upload percentage per connection type.",
    ]),
    Version(version: "0.25.0", date: "2023-10-02", changes: [
        "• Noise reduction video effect.",
    ]),
    Version(version: "0.24.0", date: "2023-10-01", changes: [
        "• Show third party licenses in About.",
        "• New video effect that randomly picks an effect.",
        "• New \"Triple\" video effect that shows the center of the video three times. Very CPU intensive right now so might be removed or reworked later on.",
        "• Gray buttons instead of blue for less distractions.",
        "• Increased maximum number of buttons from 8 to 10 (as zoom slider was removed).",
        "• BELABOX help in URL view.",
    ]),
    Version(version: "0.23.0", date: "2023-09-30", changes: [
        "• Zoom buttons instead of slider.",
        "• Rework start/stop at enter/exit background. Still problematic.",
        "• Fix audio 100 dB bug.",
    ]),
    Version(version: "0.22.0", date: "2023-09-28", changes: [
        "• Big refactoring. Hopefully didn't introduce too many bugs.",
        "• Import and export settings.",
        "• More SRT URL validation.",
        "• Allow reorder stream entries.",
        "• White viewers and chat icons with text \"Not configured\"  if channel name/id is not configured.",
        "• Higher contrast in scene picker.",
    ]),
    Version(version: "0.21.0", date: "2023-09-26", changes: [
        "• Fix startup crash when default settings are used.",
    ]),
    Version(version: "0.20.0", date: "2023-09-26", changes: [
        "• Show significant messages in a toast.",
        "• Save setting (if valid) when pressing \"Back\".",
    ]),
    Version(version: "0.19.0", date: "2023-09-25", changes: [
        "• First version that works with BELABOX cloud. Both SRT and SRTLA with H.265/HEVC works.",
    ]),
    Version(version: "0.18.0", date: "2023-09-24", changes: [
        "• Use SRT(LA) query parameters.",
    ]),
    Version(version: "0.17.0", date: "2023-09-24", changes: [
        "• SRTLA debug logs.",
        "• Clear log button.",
        "• Enable/disable debug logging.",
    ]),
    Version(version: "0.16.0", date: "2023-09-24", changes: [
        "• H.265/HEVC works. Tested with SRT and SRTLA.",
        "• Disable autocorrection on URL text field.",
    ]),
    Version(version: "0.15.0", date: "2023-09-24", changes: [
        "• Revert multi line URL as submit (pressing return) does not work.",
    ]),
    Version(version: "0.14.0", date: "2023-09-23", changes: [
        "• SRTLA that hopefully works. Only tested locally. Would be great if someone can test it with real setup.",
        "• Audio level in settings.",
        "• Show URL on multiple lines if it doesn't fit on one (for readability).",
    ]),
    Version(version: "0.13.0", date: "2023-09-23", changes: [
        "• Audio level meter local overlay.",
        "• More help in settings.",
    ]),
    Version(version: "0.12.0", date: "2023-09-23", changes: [
        "• Show longer chat names (before truncating).",
        "• SRTLA works (locally, not tested cloud). Fixed prioritization between registered interfaces.",
        "• Always restart stream when transitioning from background to foreground. Seems to fix hangs. Of what I understand video capture is prohibited in background anyway.",
    ]),
    Version(version: "0.11.0", date: "2023-09-22", changes: []),
    Version(version: "0.10.0", date: "2023-09-22", changes: []),
    Version(version: "0.9.0", date: "2023-09-21", changes: []),
    Version(version: "0.8.0", date: "2023-09-21", changes: []),
    Version(version: "0.7.0", date: "2023-09-20", changes: []),
    Version(version: "0.6.0", date: "2023-09-19", changes: []),
    Version(version: "0.5.0", date: "2023-09-18", changes: []),
    Version(version: "0.4.0", date: "2023-09-18", changes: []),
    Version(version: "0.3.0", date: "2023-09-18", changes: []),
    Version(version: "0.2.0", date: "2023-09-18", changes: []),
    Version(version: "0.1.0", date: "2023-09-17", changes: []),
]

// swiftlint:enable line_length

struct AboutVersionHistorySettingsView: View {
    var body: some View {
        ScrollView {
            HStack {
                LazyVStack(alignment: .leading) {
                    ForEach(versions, id: \.version) { version in
                        Text("\(version.version) - \(version.date)")
                            .font(.title2)
                            .padding()
                        VStack(alignment: .leading) {
                            ForEach(version.changes, id: \.self) { change in
                                Text(change)
                            }
                        }
                    }
                    Spacer()
                }
                .padding()
                Spacer()
            }
        }
        .navigationTitle("Version history")
        .toolbar {
            SettingsToolbar()
        }
    }
}
