disabled_rules:
  - function_parameter_count
  - type_name
  - large_tuple
  - identifier_name
  - file_length
  - trailing_comma
  - opening_brace
  - type_body_length
  - cyclomatic_complexity
  - function_body_length
  - force_cast
  - closure_parameter_position
  - non_optional_string_data_conversion