// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: keys.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum Keys_Role: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case none // = 0
  case service // = 1
  case owner // = 2
  case driver // = 3
  case fm // = 4
  case vehicleMonitor // = 5
  case chargingManager // = 6
  case UNRECOGNIZED(Int)

  init() {
    self = .none
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .none
    case 1: self = .service
    case 2: self = .owner
    case 3: self = .driver
    case 4: self = .fm
    case 5: self = .vehicleMonitor
    case 6: self = .chargingManager
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .none: return 0
    case .service: return 1
    case .owner: return 2
    case .driver: return 3
    case .fm: return 4
    case .vehicleMonitor: return 5
    case .chargingManager: return 6
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Keys_Role] = [
    .none,
    .service,
    .owner,
    .driver,
    .fm,
    .vehicleMonitor,
    .chargingManager,
  ]

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Keys_Role: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "ROLE_NONE"),
    1: .same(proto: "ROLE_SERVICE"),
    2: .same(proto: "ROLE_OWNER"),
    3: .same(proto: "ROLE_DRIVER"),
    4: .same(proto: "ROLE_FM"),
    5: .same(proto: "ROLE_VEHICLE_MONITOR"),
    6: .same(proto: "ROLE_CHARGING_MANAGER"),
  ]
}
