// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: live_streaming.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// live_streaming.proto/Open GoPro, Version 2.0 (C) Copyright 2021 GoPro, Inc. (http://gopro.com/OpenGoPro). 

// This copyright was auto-generated on Mon Nov  4 18:00:55 UTC 2024 

//**********************************************************************************************************************
//
// This file is automatically generated!!! Do not modify manually.
//
//********************************************************************************************************************

//*
// Defines the structure of protobuf messages for working with Live Streams

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum OpenGopro_EnumLens: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
  case lensWide = 0
  case lensLinear = 4
  case lensSuperview = 3

  init() {
    self = .lensWide
  }

}

enum OpenGopro_EnumLiveStreamError: Int, SwiftProtobuf.Enum, Swift.CaseIterable {

  /// No error (success)
  case liveStreamErrorNone = 0

  /// General network error during the stream
  case liveStreamErrorNetwork = 1

  /// Startup error: bad URL or valid with live stream server
  case liveStreamErrorCreatestream = 2

  /// Not enough memory on camera to complete task
  case liveStreamErrorOutofmemory = 3

  /// Failed to get stream from low level camera system
  case liveStreamErrorInputstream = 4

  /// No internet access detected on startup of streamer
  case liveStreamErrorInternet = 5

  /// Error occured in linux networking stack. Usually means the server closed the connection
  case liveStreamErrorOsnetwork = 6

  /// Timed out attemping to connect to the wifi network when attemping live stream
  case liveStreamErrorSelectednetworktimeout = 7

  /// SSL handshake failed (commonly caused due to incorrect time / time zone)
  case liveStreamErrorSslHandshake = 8

  /// Low level camera system rejected attempt to start live stream
  case liveStreamErrorCameraBlocked = 9

  /// Unknown
  case liveStreamErrorUnknown = 10

  /// Can not perform livestream because sd card is full
  case liveStreamErrorSdCardFull = 40

  /// Livestream stopped because sd card was removed
  case liveStreamErrorSdCardRemoved = 41

  init() {
    self = .liveStreamErrorNone
  }

}

enum OpenGopro_EnumLiveStreamStatus: Int, SwiftProtobuf.Enum, Swift.CaseIterable {

  /// Initial status. Livestream has not yet been configured
  case liveStreamStateIdle = 0

  /// Livestream is being configured
  case liveStreamStateConfig = 1

  /// Livestream has finished configuration and is ready to start streaming
  case liveStreamStateReady = 2

  /// Livestream is actively streaming
  case liveStreamStateStreaming = 3

  /// Live stream is exiting. No errors occured.
  case liveStreamStateCompleteStayOn = 4

  /// Live stream is exiting. An error occurred.
  case liveStreamStateFailedStayOn = 5

  /// An error occurred during livestream and stream is attempting to reconnect.
  case liveStreamStateReconnecting = 6

  /// Live stream setup is unavailable due to camera lens configuration
  case liveStreamStateUnavailable = 7

  init() {
    self = .liveStreamStateIdle
  }

}

enum OpenGopro_EnumRegisterLiveStreamStatus: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
  case registerLiveStreamStatusStatus = 1
  case registerLiveStreamStatusError = 2
  case registerLiveStreamStatusMode = 3
  case registerLiveStreamStatusBitrate = 4

  init() {
    self = .registerLiveStreamStatusStatus
  }

}

enum OpenGopro_EnumWindowSize: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
  case windowSize480 = 4
  case windowSize720 = 7
  case windowSize1080 = 12

  init() {
    self = .windowSize480
  }

}

///*
/// Live Stream status
///
/// Sent either:
///
///   - As a synchronous response to initial @ref RequestGetLiveStreamStatus
///   - As an asynchronous notifications registered for via @ref RequestGetLiveStreamStatus
struct OpenGopro_NotifyLiveStreamStatus: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Live stream status
  var liveStreamStatus: OpenGopro_EnumLiveStreamStatus {
    get {return _liveStreamStatus ?? .liveStreamStateIdle}
    set {_liveStreamStatus = newValue}
  }
  /// Returns true if `liveStreamStatus` has been explicitly set.
  var hasLiveStreamStatus: Bool {return self._liveStreamStatus != nil}
  /// Clears the value of `liveStreamStatus`. Subsequent reads from it will return its default value.
  mutating func clearLiveStreamStatus() {self._liveStreamStatus = nil}

  /// Live stream error
  var liveStreamError: OpenGopro_EnumLiveStreamError {
    get {return _liveStreamError ?? .liveStreamErrorNone}
    set {_liveStreamError = newValue}
  }
  /// Returns true if `liveStreamError` has been explicitly set.
  var hasLiveStreamError: Bool {return self._liveStreamError != nil}
  /// Clears the value of `liveStreamError`. Subsequent reads from it will return its default value.
  mutating func clearLiveStreamError() {self._liveStreamError = nil}

  /// Is live stream encoding?
  var liveStreamEncode: Bool {
    get {return _liveStreamEncode ?? false}
    set {_liveStreamEncode = newValue}
  }
  /// Returns true if `liveStreamEncode` has been explicitly set.
  var hasLiveStreamEncode: Bool {return self._liveStreamEncode != nil}
  /// Clears the value of `liveStreamEncode`. Subsequent reads from it will return its default value.
  mutating func clearLiveStreamEncode() {self._liveStreamEncode = nil}

  /// Live stream bitrate (Kbps)
  var liveStreamBitrate: Int32 {
    get {return _liveStreamBitrate ?? 0}
    set {_liveStreamBitrate = newValue}
  }
  /// Returns true if `liveStreamBitrate` has been explicitly set.
  var hasLiveStreamBitrate: Bool {return self._liveStreamBitrate != nil}
  /// Clears the value of `liveStreamBitrate`. Subsequent reads from it will return its default value.
  mutating func clearLiveStreamBitrate() {self._liveStreamBitrate = nil}

  /// Set of currently supported resolutions
  var liveStreamWindowSizeSupportedArray: [OpenGopro_EnumWindowSize] = []

  /// Does the camera support encoding while live streaming?
  var liveStreamEncodeSupported: Bool {
    get {return _liveStreamEncodeSupported ?? false}
    set {_liveStreamEncodeSupported = newValue}
  }
  /// Returns true if `liveStreamEncodeSupported` has been explicitly set.
  var hasLiveStreamEncodeSupported: Bool {return self._liveStreamEncodeSupported != nil}
  /// Clears the value of `liveStreamEncodeSupported`. Subsequent reads from it will return its default value.
  mutating func clearLiveStreamEncodeSupported() {self._liveStreamEncodeSupported = nil}

  /// Is the Max Lens feature NOT supported?
  var liveStreamMaxLensUnsupported: Bool {
    get {return _liveStreamMaxLensUnsupported ?? false}
    set {_liveStreamMaxLensUnsupported = newValue}
  }
  /// Returns true if `liveStreamMaxLensUnsupported` has been explicitly set.
  var hasLiveStreamMaxLensUnsupported: Bool {return self._liveStreamMaxLensUnsupported != nil}
  /// Clears the value of `liveStreamMaxLensUnsupported`. Subsequent reads from it will return its default value.
  mutating func clearLiveStreamMaxLensUnsupported() {self._liveStreamMaxLensUnsupported = nil}

  /// Camera-defined minimum bitrate (static) (Kbps)
  var liveStreamMinimumStreamBitrate: Int32 {
    get {return _liveStreamMinimumStreamBitrate ?? 0}
    set {_liveStreamMinimumStreamBitrate = newValue}
  }
  /// Returns true if `liveStreamMinimumStreamBitrate` has been explicitly set.
  var hasLiveStreamMinimumStreamBitrate: Bool {return self._liveStreamMinimumStreamBitrate != nil}
  /// Clears the value of `liveStreamMinimumStreamBitrate`. Subsequent reads from it will return its default value.
  mutating func clearLiveStreamMinimumStreamBitrate() {self._liveStreamMinimumStreamBitrate = nil}

  /// Camera-defined maximum bitrate (static) (Kbps)
  var liveStreamMaximumStreamBitrate: Int32 {
    get {return _liveStreamMaximumStreamBitrate ?? 0}
    set {_liveStreamMaximumStreamBitrate = newValue}
  }
  /// Returns true if `liveStreamMaximumStreamBitrate` has been explicitly set.
  var hasLiveStreamMaximumStreamBitrate: Bool {return self._liveStreamMaximumStreamBitrate != nil}
  /// Clears the value of `liveStreamMaximumStreamBitrate`. Subsequent reads from it will return its default value.
  mutating func clearLiveStreamMaximumStreamBitrate() {self._liveStreamMaximumStreamBitrate = nil}

  /// Does camera support setting lens for live streaming?
  var liveStreamLensSupported: Bool {
    get {return _liveStreamLensSupported ?? false}
    set {_liveStreamLensSupported = newValue}
  }
  /// Returns true if `liveStreamLensSupported` has been explicitly set.
  var hasLiveStreamLensSupported: Bool {return self._liveStreamLensSupported != nil}
  /// Clears the value of `liveStreamLensSupported`. Subsequent reads from it will return its default value.
  mutating func clearLiveStreamLensSupported() {self._liveStreamLensSupported = nil}

  /// Set of currently supported FOV options
  var liveStreamLensSupportedArray: [OpenGopro_EnumLens] = []

  /// Does the camera support live stream protune settings
  var liveStreamProtuneSupported: Bool {
    get {return _liveStreamProtuneSupported ?? false}
    set {_liveStreamProtuneSupported = newValue}
  }
  /// Returns true if `liveStreamProtuneSupported` has been explicitly set.
  var hasLiveStreamProtuneSupported: Bool {return self._liveStreamProtuneSupported != nil}
  /// Clears the value of `liveStreamProtuneSupported`. Subsequent reads from it will return its default value.
  mutating func clearLiveStreamProtuneSupported() {self._liveStreamProtuneSupported = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _liveStreamStatus: OpenGopro_EnumLiveStreamStatus? = nil
  fileprivate var _liveStreamError: OpenGopro_EnumLiveStreamError? = nil
  fileprivate var _liveStreamEncode: Bool? = nil
  fileprivate var _liveStreamBitrate: Int32? = nil
  fileprivate var _liveStreamEncodeSupported: Bool? = nil
  fileprivate var _liveStreamMaxLensUnsupported: Bool? = nil
  fileprivate var _liveStreamMinimumStreamBitrate: Int32? = nil
  fileprivate var _liveStreamMaximumStreamBitrate: Int32? = nil
  fileprivate var _liveStreamLensSupported: Bool? = nil
  fileprivate var _liveStreamProtuneSupported: Bool? = nil
}

///*
/// Get the current livestream status (and optionally register for future status changes)
///
/// Response: @ref NotifyLiveStreamStatus
///
/// Notification: @ref NotifyLiveStreamStatus
struct OpenGopro_RequestGetLiveStreamStatus: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Array of live stream statuses to be notified about
  var registerLiveStreamStatus: [OpenGopro_EnumRegisterLiveStreamStatus] = []

  /// Array of live stream statuses to stop being notified about
  var unregisterLiveStreamStatus: [OpenGopro_EnumRegisterLiveStreamStatus] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

///*
/// Configure Live Streaming
///
/// Response: @ref ResponseGeneric
struct OpenGopro_RequestSetLiveStreamMode: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// RTMP(S) URL used for live stream
  var url: String {
    get {return _url ?? String()}
    set {_url = newValue}
  }
  /// Returns true if `url` has been explicitly set.
  var hasURL: Bool {return self._url != nil}
  /// Clears the value of `url`. Subsequent reads from it will return its default value.
  mutating func clearURL() {self._url = nil}

  /// Save media to sdcard while streaming?
  var encode: Bool {
    get {return _encode ?? false}
    set {_encode = newValue}
  }
  /// Returns true if `encode` has been explicitly set.
  var hasEncode: Bool {return self._encode != nil}
  /// Clears the value of `encode`. Subsequent reads from it will return its default value.
  mutating func clearEncode() {self._encode = nil}

  ///*
  /// Resolution to use for live stream
  ///
  /// The set of supported resolutions is only available from the `live_stream_window_size_supported_array`
  /// in @ref NotifyLiveStreamStatus.
  var windowSize: OpenGopro_EnumWindowSize {
    get {return _windowSize ?? .windowSize480}
    set {_windowSize = newValue}
  }
  /// Returns true if `windowSize` has been explicitly set.
  var hasWindowSize: Bool {return self._windowSize != nil}
  /// Clears the value of `windowSize`. Subsequent reads from it will return its default value.
  mutating func clearWindowSize() {self._windowSize = nil}

  /// Certificate for servers that require it in PEM format
  var cert: Data {
    get {return _cert ?? Data()}
    set {_cert = newValue}
  }
  /// Returns true if `cert` has been explicitly set.
  var hasCert: Bool {return self._cert != nil}
  /// Clears the value of `cert`. Subsequent reads from it will return its default value.
  mutating func clearCert() {self._cert = nil}

  /// Minimum desired bitrate (may or may not be honored)
  var minimumBitrate: Int32 {
    get {return _minimumBitrate ?? 0}
    set {_minimumBitrate = newValue}
  }
  /// Returns true if `minimumBitrate` has been explicitly set.
  var hasMinimumBitrate: Bool {return self._minimumBitrate != nil}
  /// Clears the value of `minimumBitrate`. Subsequent reads from it will return its default value.
  mutating func clearMinimumBitrate() {self._minimumBitrate = nil}

  /// Maximum desired bitrate (may or may not be honored)
  var maximumBitrate: Int32 {
    get {return _maximumBitrate ?? 0}
    set {_maximumBitrate = newValue}
  }
  /// Returns true if `maximumBitrate` has been explicitly set.
  var hasMaximumBitrate: Bool {return self._maximumBitrate != nil}
  /// Clears the value of `maximumBitrate`. Subsequent reads from it will return its default value.
  mutating func clearMaximumBitrate() {self._maximumBitrate = nil}

  /// Starting bitrate
  var startingBitrate: Int32 {
    get {return _startingBitrate ?? 0}
    set {_startingBitrate = newValue}
  }
  /// Returns true if `startingBitrate` has been explicitly set.
  var hasStartingBitrate: Bool {return self._startingBitrate != nil}
  /// Clears the value of `startingBitrate`. Subsequent reads from it will return its default value.
  mutating func clearStartingBitrate() {self._startingBitrate = nil}

  ///*
  /// Lens to use for live stream
  ///
  /// The set of supported lenses is only available from the  `live_stream_lens_supported_array`
  /// in @ref NotifyLiveStreamStatus.
  var lens: OpenGopro_EnumLens {
    get {return _lens ?? .lensWide}
    set {_lens = newValue}
  }
  /// Returns true if `lens` has been explicitly set.
  var hasLens: Bool {return self._lens != nil}
  /// Clears the value of `lens`. Subsequent reads from it will return its default value.
  mutating func clearLens() {self._lens = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _url: String? = nil
  fileprivate var _encode: Bool? = nil
  fileprivate var _windowSize: OpenGopro_EnumWindowSize? = nil
  fileprivate var _cert: Data? = nil
  fileprivate var _minimumBitrate: Int32? = nil
  fileprivate var _maximumBitrate: Int32? = nil
  fileprivate var _startingBitrate: Int32? = nil
  fileprivate var _lens: OpenGopro_EnumLens? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "open_gopro"

extension OpenGopro_EnumLens: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0LENS_WIDE\0\u{2}\u{3}LENS_SUPERVIEW\0\u{1}LENS_LINEAR\0")
}

extension OpenGopro_EnumLiveStreamError: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0LIVE_STREAM_ERROR_NONE\0\u{1}LIVE_STREAM_ERROR_NETWORK\0\u{1}LIVE_STREAM_ERROR_CREATESTREAM\0\u{1}LIVE_STREAM_ERROR_OUTOFMEMORY\0\u{1}LIVE_STREAM_ERROR_INPUTSTREAM\0\u{1}LIVE_STREAM_ERROR_INTERNET\0\u{1}LIVE_STREAM_ERROR_OSNETWORK\0\u{1}LIVE_STREAM_ERROR_SELECTEDNETWORKTIMEOUT\0\u{1}LIVE_STREAM_ERROR_SSL_HANDSHAKE\0\u{1}LIVE_STREAM_ERROR_CAMERA_BLOCKED\0\u{1}LIVE_STREAM_ERROR_UNKNOWN\0\u{2}\u{1e}LIVE_STREAM_ERROR_SD_CARD_FULL\0\u{1}LIVE_STREAM_ERROR_SD_CARD_REMOVED\0")
}

extension OpenGopro_EnumLiveStreamStatus: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0LIVE_STREAM_STATE_IDLE\0\u{1}LIVE_STREAM_STATE_CONFIG\0\u{1}LIVE_STREAM_STATE_READY\0\u{1}LIVE_STREAM_STATE_STREAMING\0\u{1}LIVE_STREAM_STATE_COMPLETE_STAY_ON\0\u{1}LIVE_STREAM_STATE_FAILED_STAY_ON\0\u{1}LIVE_STREAM_STATE_RECONNECTING\0\u{1}LIVE_STREAM_STATE_UNAVAILABLE\0")
}

extension OpenGopro_EnumRegisterLiveStreamStatus: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}REGISTER_LIVE_STREAM_STATUS_STATUS\0\u{1}REGISTER_LIVE_STREAM_STATUS_ERROR\0\u{1}REGISTER_LIVE_STREAM_STATUS_MODE\0\u{1}REGISTER_LIVE_STREAM_STATUS_BITRATE\0")
}

extension OpenGopro_EnumWindowSize: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{4}WINDOW_SIZE_480\0\u{2}\u{3}WINDOW_SIZE_720\0\u{2}\u{5}WINDOW_SIZE_1080\0")
}

extension OpenGopro_NotifyLiveStreamStatus: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".NotifyLiveStreamStatus"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}live_stream_status\0\u{3}live_stream_error\0\u{3}live_stream_encode\0\u{3}live_stream_bitrate\0\u{3}live_stream_window_size_supported_array\0\u{3}live_stream_encode_supported\0\u{3}live_stream_max_lens_unsupported\0\u{3}live_stream_minimum_stream_bitrate\0\u{3}live_stream_maximum_stream_bitrate\0\u{3}live_stream_lens_supported\0\u{3}live_stream_lens_supported_array\0\u{4}\u{2}live_stream_protune_supported\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._liveStreamStatus) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self._liveStreamError) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self._liveStreamEncode) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self._liveStreamBitrate) }()
      case 5: try { try decoder.decodeRepeatedEnumField(value: &self.liveStreamWindowSizeSupportedArray) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self._liveStreamEncodeSupported) }()
      case 7: try { try decoder.decodeSingularBoolField(value: &self._liveStreamMaxLensUnsupported) }()
      case 8: try { try decoder.decodeSingularInt32Field(value: &self._liveStreamMinimumStreamBitrate) }()
      case 9: try { try decoder.decodeSingularInt32Field(value: &self._liveStreamMaximumStreamBitrate) }()
      case 10: try { try decoder.decodeSingularBoolField(value: &self._liveStreamLensSupported) }()
      case 11: try { try decoder.decodeRepeatedEnumField(value: &self.liveStreamLensSupportedArray) }()
      case 13: try { try decoder.decodeSingularBoolField(value: &self._liveStreamProtuneSupported) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._liveStreamStatus {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._liveStreamError {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._liveStreamEncode {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._liveStreamBitrate {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 4)
    } }()
    if !self.liveStreamWindowSizeSupportedArray.isEmpty {
      try visitor.visitRepeatedEnumField(value: self.liveStreamWindowSizeSupportedArray, fieldNumber: 5)
    }
    try { if let v = self._liveStreamEncodeSupported {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._liveStreamMaxLensUnsupported {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._liveStreamMinimumStreamBitrate {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._liveStreamMaximumStreamBitrate {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 9)
    } }()
    try { if let v = self._liveStreamLensSupported {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 10)
    } }()
    if !self.liveStreamLensSupportedArray.isEmpty {
      try visitor.visitRepeatedEnumField(value: self.liveStreamLensSupportedArray, fieldNumber: 11)
    }
    try { if let v = self._liveStreamProtuneSupported {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 13)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: OpenGopro_NotifyLiveStreamStatus, rhs: OpenGopro_NotifyLiveStreamStatus) -> Bool {
    if lhs._liveStreamStatus != rhs._liveStreamStatus {return false}
    if lhs._liveStreamError != rhs._liveStreamError {return false}
    if lhs._liveStreamEncode != rhs._liveStreamEncode {return false}
    if lhs._liveStreamBitrate != rhs._liveStreamBitrate {return false}
    if lhs.liveStreamWindowSizeSupportedArray != rhs.liveStreamWindowSizeSupportedArray {return false}
    if lhs._liveStreamEncodeSupported != rhs._liveStreamEncodeSupported {return false}
    if lhs._liveStreamMaxLensUnsupported != rhs._liveStreamMaxLensUnsupported {return false}
    if lhs._liveStreamMinimumStreamBitrate != rhs._liveStreamMinimumStreamBitrate {return false}
    if lhs._liveStreamMaximumStreamBitrate != rhs._liveStreamMaximumStreamBitrate {return false}
    if lhs._liveStreamLensSupported != rhs._liveStreamLensSupported {return false}
    if lhs.liveStreamLensSupportedArray != rhs.liveStreamLensSupportedArray {return false}
    if lhs._liveStreamProtuneSupported != rhs._liveStreamProtuneSupported {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension OpenGopro_RequestGetLiveStreamStatus: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RequestGetLiveStreamStatus"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}register_live_stream_status\0\u{3}unregister_live_stream_status\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedEnumField(value: &self.registerLiveStreamStatus) }()
      case 2: try { try decoder.decodeRepeatedEnumField(value: &self.unregisterLiveStreamStatus) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.registerLiveStreamStatus.isEmpty {
      try visitor.visitRepeatedEnumField(value: self.registerLiveStreamStatus, fieldNumber: 1)
    }
    if !self.unregisterLiveStreamStatus.isEmpty {
      try visitor.visitRepeatedEnumField(value: self.unregisterLiveStreamStatus, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: OpenGopro_RequestGetLiveStreamStatus, rhs: OpenGopro_RequestGetLiveStreamStatus) -> Bool {
    if lhs.registerLiveStreamStatus != rhs.registerLiveStreamStatus {return false}
    if lhs.unregisterLiveStreamStatus != rhs.unregisterLiveStreamStatus {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension OpenGopro_RequestSetLiveStreamMode: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RequestSetLiveStreamMode"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}url\0\u{1}encode\0\u{3}window_size\0\u{2}\u{3}cert\0\u{3}minimum_bitrate\0\u{3}maximum_bitrate\0\u{3}starting_bitrate\0\u{1}lens\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._url) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self._encode) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self._windowSize) }()
      case 6: try { try decoder.decodeSingularBytesField(value: &self._cert) }()
      case 7: try { try decoder.decodeSingularInt32Field(value: &self._minimumBitrate) }()
      case 8: try { try decoder.decodeSingularInt32Field(value: &self._maximumBitrate) }()
      case 9: try { try decoder.decodeSingularInt32Field(value: &self._startingBitrate) }()
      case 10: try { try decoder.decodeSingularEnumField(value: &self._lens) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._url {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._encode {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._windowSize {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._cert {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._minimumBitrate {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._maximumBitrate {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._startingBitrate {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 9)
    } }()
    try { if let v = self._lens {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 10)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: OpenGopro_RequestSetLiveStreamMode, rhs: OpenGopro_RequestSetLiveStreamMode) -> Bool {
    if lhs._url != rhs._url {return false}
    if lhs._encode != rhs._encode {return false}
    if lhs._windowSize != rhs._windowSize {return false}
    if lhs._cert != rhs._cert {return false}
    if lhs._minimumBitrate != rhs._minimumBitrate {return false}
    if lhs._maximumBitrate != rhs._maximumBitrate {return false}
    if lhs._startingBitrate != rhs._startingBitrate {return false}
    if lhs._lens != rhs._lens {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
