// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: network_management.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// network_management.proto/Open GoPro, Version 2.0 (C) Copyright 2021 GoPro, Inc. (http://gopro.com/OpenGoPro). 

// This copyright was auto-generated on Mon Nov  4 18:00:55 UTC 2024 

//**********************************************************************************************************************
//
// This file is automatically generated!!! Do not modify manually.
//
//********************************************************************************************************************

//*
// Defines the structure of protobuf messages for network management

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum OpenGopro_EnumProvisioning: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
  case provisioningUnknown = 0
  case provisioningNeverStarted = 1
  case provisioningStarted = 2
  case provisioningAbortedBySystem = 3
  case provisioningCancelledByUser = 4
  case provisioningSuccessNewAp = 5
  case provisioningSuccessOldAp = 6
  case provisioningErrorFailedToAssociate = 7
  case provisioningErrorPasswordAuth = 8
  case provisioningErrorEulaBlocking = 9
  case provisioningErrorNoInternet = 10
  case provisioningErrorUnsupportedType = 11

  init() {
    self = .provisioningUnknown
  }

}

enum OpenGopro_EnumScanning: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
  case scanningUnknown = 0
  case scanningNeverStarted = 1
  case scanningStarted = 2
  case scanningAbortedBySystem = 3
  case scanningCancelledByUser = 4
  case scanningSuccess = 5

  init() {
    self = .scanningUnknown
  }

}

enum OpenGopro_EnumScanEntryFlags: Int, SwiftProtobuf.Enum, Swift.CaseIterable {

  /// This network does not require authentication
  case scanFlagOpen = 0

  /// This network requires authentication
  case scanFlagAuthenticated = 1

  /// This network has been previously provisioned
  case scanFlagConfigured = 2
  case scanFlagBestSsid = 4

  /// Camera is connected to this AP
  case scanFlagAssociated = 8
  case scanFlagUnsupportedType = 16

  init() {
    self = .scanFlagOpen
  }

}

enum OpenGopro_EnumPairingFinishState: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
  case success = 0
  case failed = 1

  init() {
    self = .success
  }

}

///
/// Provision state notification
///
/// Sent during provisioning triggered via @ref RequestConnect or @ref RequestConnectNew
struct OpenGopro_NotifProvisioningState: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Provisioning / connection state
  var provisioningState: OpenGopro_EnumProvisioning {
    get {return _provisioningState ?? .provisioningUnknown}
    set {_provisioningState = newValue}
  }
  /// Returns true if `provisioningState` has been explicitly set.
  var hasProvisioningState: Bool {return self._provisioningState != nil}
  /// Clears the value of `provisioningState`. Subsequent reads from it will return its default value.
  mutating func clearProvisioningState() {self._provisioningState = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _provisioningState: OpenGopro_EnumProvisioning? = nil
}

///
/// Scanning state notification
///
/// Triggered via @ref RequestStartScan
struct OpenGopro_NotifStartScanning: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Scanning state
  var scanningState: OpenGopro_EnumScanning {
    get {return _scanningState ?? .scanningUnknown}
    set {_scanningState = newValue}
  }
  /// Returns true if `scanningState` has been explicitly set.
  var hasScanningState: Bool {return self._scanningState != nil}
  /// Clears the value of `scanningState`. Subsequent reads from it will return its default value.
  mutating func clearScanningState() {self._scanningState = nil}

  /// ID associated with scan results (included if scan was successful)
  var scanID: Int32 {
    get {return _scanID ?? 0}
    set {_scanID = newValue}
  }
  /// Returns true if `scanID` has been explicitly set.
  var hasScanID: Bool {return self._scanID != nil}
  /// Clears the value of `scanID`. Subsequent reads from it will return its default value.
  mutating func clearScanID() {self._scanID = nil}

  /// Number of APs found during scan (included if scan was successful)
  var totalEntries: Int32 {
    get {return _totalEntries ?? 0}
    set {_totalEntries = newValue}
  }
  /// Returns true if `totalEntries` has been explicitly set.
  var hasTotalEntries: Bool {return self._totalEntries != nil}
  /// Clears the value of `totalEntries`. Subsequent reads from it will return its default value.
  mutating func clearTotalEntries() {self._totalEntries = nil}

  /// Total count of camera's provisioned SSIDs
  var totalConfiguredSsid: Int32 {
    get {return _totalConfiguredSsid ?? 0}
    set {_totalConfiguredSsid = newValue}
  }
  /// Returns true if `totalConfiguredSsid` has been explicitly set.
  var hasTotalConfiguredSsid: Bool {return self._totalConfiguredSsid != nil}
  /// Clears the value of `totalConfiguredSsid`. Subsequent reads from it will return its default value.
  mutating func clearTotalConfiguredSsid() {self._totalConfiguredSsid = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _scanningState: OpenGopro_EnumScanning? = nil
  fileprivate var _scanID: Int32? = nil
  fileprivate var _totalEntries: Int32? = nil
  fileprivate var _totalConfiguredSsid: Int32? = nil
}

///*
/// Connect to (but do not authenticate with) an Access Point
///
/// This is intended to be used to connect to a previously-connected Access Point
///
/// Response: @ref ResponseConnect
///
/// Notification: @ref NotifProvisioningState sent periodically as provisioning state changes
struct OpenGopro_RequestConnect: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// AP SSID
  var ssid: String {
    get {return _ssid ?? String()}
    set {_ssid = newValue}
  }
  /// Returns true if `ssid` has been explicitly set.
  var hasSsid: Bool {return self._ssid != nil}
  /// Clears the value of `ssid`. Subsequent reads from it will return its default value.
  mutating func clearSsid() {self._ssid = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _ssid: String? = nil
}

///*
/// Connect to and authenticate with an Access Point
///
/// This is only intended to be used if the AP is not previously provisioned.
///
/// Response: @ref ResponseConnectNew sent immediately
///
/// Notification: @ref NotifProvisioningState sent periodically as provisioning state changes
struct OpenGopro_RequestConnectNew: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// AP SSID
  var ssid: String {
    get {return _ssid ?? String()}
    set {_ssid = newValue}
  }
  /// Returns true if `ssid` has been explicitly set.
  var hasSsid: Bool {return self._ssid != nil}
  /// Clears the value of `ssid`. Subsequent reads from it will return its default value.
  mutating func clearSsid() {self._ssid = nil}

  /// AP password
  var password: String {
    get {return _password ?? String()}
    set {_password = newValue}
  }
  /// Returns true if `password` has been explicitly set.
  var hasPassword: Bool {return self._password != nil}
  /// Clears the value of `password`. Subsequent reads from it will return its default value.
  mutating func clearPassword() {self._password = nil}

  /// Static IP address
  var staticIp: Data {
    get {return _staticIp ?? Data()}
    set {_staticIp = newValue}
  }
  /// Returns true if `staticIp` has been explicitly set.
  var hasStaticIp: Bool {return self._staticIp != nil}
  /// Clears the value of `staticIp`. Subsequent reads from it will return its default value.
  mutating func clearStaticIp() {self._staticIp = nil}

  /// Gateway IP address
  var gateway: Data {
    get {return _gateway ?? Data()}
    set {_gateway = newValue}
  }
  /// Returns true if `gateway` has been explicitly set.
  var hasGateway: Bool {return self._gateway != nil}
  /// Clears the value of `gateway`. Subsequent reads from it will return its default value.
  mutating func clearGateway() {self._gateway = nil}

  /// Subnet mask
  var subnet: Data {
    get {return _subnet ?? Data()}
    set {_subnet = newValue}
  }
  /// Returns true if `subnet` has been explicitly set.
  var hasSubnet: Bool {return self._subnet != nil}
  /// Clears the value of `subnet`. Subsequent reads from it will return its default value.
  mutating func clearSubnet() {self._subnet = nil}

  /// Primary DNS
  var dnsPrimary: Data {
    get {return _dnsPrimary ?? Data()}
    set {_dnsPrimary = newValue}
  }
  /// Returns true if `dnsPrimary` has been explicitly set.
  var hasDnsPrimary: Bool {return self._dnsPrimary != nil}
  /// Clears the value of `dnsPrimary`. Subsequent reads from it will return its default value.
  mutating func clearDnsPrimary() {self._dnsPrimary = nil}

  /// Secondary DNS
  var dnsSecondary: Data {
    get {return _dnsSecondary ?? Data()}
    set {_dnsSecondary = newValue}
  }
  /// Returns true if `dnsSecondary` has been explicitly set.
  var hasDnsSecondary: Bool {return self._dnsSecondary != nil}
  /// Clears the value of `dnsSecondary`. Subsequent reads from it will return its default value.
  mutating func clearDnsSecondary() {self._dnsSecondary = nil}

  /// Allow network configuration without internet connectivity
  var bypassEulaCheck: Bool {
    get {return _bypassEulaCheck ?? false}
    set {_bypassEulaCheck = newValue}
  }
  /// Returns true if `bypassEulaCheck` has been explicitly set.
  var hasBypassEulaCheck: Bool {return self._bypassEulaCheck != nil}
  /// Clears the value of `bypassEulaCheck`. Subsequent reads from it will return its default value.
  mutating func clearBypassEulaCheck() {self._bypassEulaCheck = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _ssid: String? = nil
  fileprivate var _password: String? = nil
  fileprivate var _staticIp: Data? = nil
  fileprivate var _gateway: Data? = nil
  fileprivate var _subnet: Data? = nil
  fileprivate var _dnsPrimary: Data? = nil
  fileprivate var _dnsSecondary: Data? = nil
  fileprivate var _bypassEulaCheck: Bool? = nil
}

///*
/// Get a list of Access Points found during a @ref RequestStartScan
///
/// Response: @ref ResponseGetApEntries
struct OpenGopro_RequestGetApEntries: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Used for paging. 0 <= start_index < @ref ResponseGetApEntries .total_entries
  var startIndex: Int32 {
    get {return _startIndex ?? 0}
    set {_startIndex = newValue}
  }
  /// Returns true if `startIndex` has been explicitly set.
  var hasStartIndex: Bool {return self._startIndex != nil}
  /// Clears the value of `startIndex`. Subsequent reads from it will return its default value.
  mutating func clearStartIndex() {self._startIndex = nil}

  /// Used for paging. Value must be < @ref ResponseGetApEntries .total_entries
  var maxEntries: Int32 {
    get {return _maxEntries ?? 0}
    set {_maxEntries = newValue}
  }
  /// Returns true if `maxEntries` has been explicitly set.
  var hasMaxEntries: Bool {return self._maxEntries != nil}
  /// Clears the value of `maxEntries`. Subsequent reads from it will return its default value.
  mutating func clearMaxEntries() {self._maxEntries = nil}

  /// ID corresponding to a set of scan results (i.e. @ref ResponseGetApEntries .scan_id)
  var scanID: Int32 {
    get {return _scanID ?? 0}
    set {_scanID = newValue}
  }
  /// Returns true if `scanID` has been explicitly set.
  var hasScanID: Bool {return self._scanID != nil}
  /// Clears the value of `scanID`. Subsequent reads from it will return its default value.
  mutating func clearScanID() {self._scanID = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _startIndex: Int32? = nil
  fileprivate var _maxEntries: Int32? = nil
  fileprivate var _scanID: Int32? = nil
}

///*
/// Request to disconnect from currently-connected AP
///
/// This drops the camera out of Station (STA) Mode and returns it to Access Point (AP) mode.
///
/// Response: @ref ResponseGeneric
struct OpenGopro_RequestReleaseNetwork: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

///*
/// Start scanning for Access Points
///
/// @note Serialization of this object is zero bytes.
///
/// Response: @ref ResponseStartScanning  are sent immediately after the camera receives this command
///
/// Notifications: @ref NotifStartScanning are sent periodically as scanning state changes. Use to detect scan complete.
struct OpenGopro_RequestStartScan: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

///*
/// The status of an attempt to connect to an Access Point
///
/// Sent as the initial response to @ref RequestConnect
struct OpenGopro_ResponseConnect: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Generic pass/fail/error info
  var result: OpenGopro_EnumResultGeneric {
    get {return _result ?? .resultUnknown}
    set {_result = newValue}
  }
  /// Returns true if `result` has been explicitly set.
  var hasResult: Bool {return self._result != nil}
  /// Clears the value of `result`. Subsequent reads from it will return its default value.
  mutating func clearResult() {self._result = nil}

  /// Provisioning/connection state
  var provisioningState: OpenGopro_EnumProvisioning {
    get {return _provisioningState ?? .provisioningUnknown}
    set {_provisioningState = newValue}
  }
  /// Returns true if `provisioningState` has been explicitly set.
  var hasProvisioningState: Bool {return self._provisioningState != nil}
  /// Clears the value of `provisioningState`. Subsequent reads from it will return its default value.
  mutating func clearProvisioningState() {self._provisioningState = nil}

  /// Network connection timeout (seconds)
  var timeoutSeconds: Int32 {
    get {return _timeoutSeconds ?? 0}
    set {_timeoutSeconds = newValue}
  }
  /// Returns true if `timeoutSeconds` has been explicitly set.
  var hasTimeoutSeconds: Bool {return self._timeoutSeconds != nil}
  /// Clears the value of `timeoutSeconds`. Subsequent reads from it will return its default value.
  mutating func clearTimeoutSeconds() {self._timeoutSeconds = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _result: OpenGopro_EnumResultGeneric? = nil
  fileprivate var _provisioningState: OpenGopro_EnumProvisioning? = nil
  fileprivate var _timeoutSeconds: Int32? = nil
}

///*
/// The status of an attempt to connect to an Access Point
///
/// Sent as the initial response to @ref RequestConnectNew
struct OpenGopro_ResponseConnectNew: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Status of Connect New request
  var result: OpenGopro_EnumResultGeneric {
    get {return _result ?? .resultUnknown}
    set {_result = newValue}
  }
  /// Returns true if `result` has been explicitly set.
  var hasResult: Bool {return self._result != nil}
  /// Clears the value of `result`. Subsequent reads from it will return its default value.
  mutating func clearResult() {self._result = nil}

  /// Current provisioning state of the network
  var provisioningState: OpenGopro_EnumProvisioning {
    get {return _provisioningState ?? .provisioningUnknown}
    set {_provisioningState = newValue}
  }
  /// Returns true if `provisioningState` has been explicitly set.
  var hasProvisioningState: Bool {return self._provisioningState != nil}
  /// Clears the value of `provisioningState`. Subsequent reads from it will return its default value.
  mutating func clearProvisioningState() {self._provisioningState = nil}

  ///*
  /// Number of seconds camera will wait before declaring a network connection attempt failed
  var timeoutSeconds: Int32 {
    get {return _timeoutSeconds ?? 0}
    set {_timeoutSeconds = newValue}
  }
  /// Returns true if `timeoutSeconds` has been explicitly set.
  var hasTimeoutSeconds: Bool {return self._timeoutSeconds != nil}
  /// Clears the value of `timeoutSeconds`. Subsequent reads from it will return its default value.
  mutating func clearTimeoutSeconds() {self._timeoutSeconds = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _result: OpenGopro_EnumResultGeneric? = nil
  fileprivate var _provisioningState: OpenGopro_EnumProvisioning? = nil
  fileprivate var _timeoutSeconds: Int32? = nil
}

///*
/// A list of scan entries describing a scanned Access Point
///
/// This is sent in response to a @ref RequestGetApEntries
struct OpenGopro_ResponseGetApEntries: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Generic pass/fail/error info
  var result: OpenGopro_EnumResultGeneric {
    get {return _result ?? .resultUnknown}
    set {_result = newValue}
  }
  /// Returns true if `result` has been explicitly set.
  var hasResult: Bool {return self._result != nil}
  /// Clears the value of `result`. Subsequent reads from it will return its default value.
  mutating func clearResult() {self._result = nil}

  /// ID associated with this batch of results
  var scanID: Int32 {
    get {return _scanID ?? 0}
    set {_scanID = newValue}
  }
  /// Returns true if `scanID` has been explicitly set.
  var hasScanID: Bool {return self._scanID != nil}
  /// Clears the value of `scanID`. Subsequent reads from it will return its default value.
  mutating func clearScanID() {self._scanID = nil}

  /// Array containing details about discovered APs
  var entries: [OpenGopro_ResponseGetApEntries.ScanEntry] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  ///*
  /// An individual Scan Entry in a @ref ResponseGetApEntries response
  ///
  /// @note When `scan_entry_flags` contains `SCAN_FLAG_CONFIGURED`, it is an indication that this network has already been provisioned.
  struct ScanEntry: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// AP SSID
    var ssid: String {
      get {return _ssid ?? String()}
      set {_ssid = newValue}
    }
    /// Returns true if `ssid` has been explicitly set.
    var hasSsid: Bool {return self._ssid != nil}
    /// Clears the value of `ssid`. Subsequent reads from it will return its default value.
    mutating func clearSsid() {self._ssid = nil}

    /// Signal strength (3 bars: >-70 dBm; 2 bars: >-85 dBm; 1 bar: <=-85 dBm)
    var signalStrengthBars: Int32 {
      get {return _signalStrengthBars ?? 0}
      set {_signalStrengthBars = newValue}
    }
    /// Returns true if `signalStrengthBars` has been explicitly set.
    var hasSignalStrengthBars: Bool {return self._signalStrengthBars != nil}
    /// Clears the value of `signalStrengthBars`. Subsequent reads from it will return its default value.
    mutating func clearSignalStrengthBars() {self._signalStrengthBars = nil}

    /// Signal frequency (MHz)
    var signalFrequencyMhz: Int32 {
      get {return _signalFrequencyMhz ?? 0}
      set {_signalFrequencyMhz = newValue}
    }
    /// Returns true if `signalFrequencyMhz` has been explicitly set.
    var hasSignalFrequencyMhz: Bool {return self._signalFrequencyMhz != nil}
    /// Clears the value of `signalFrequencyMhz`. Subsequent reads from it will return its default value.
    mutating func clearSignalFrequencyMhz() {self._signalFrequencyMhz = nil}

    /// Bitmasked value from @ref EnumScanEntryFlags
    var scanEntryFlags: Int32 {
      get {return _scanEntryFlags ?? 0}
      set {_scanEntryFlags = newValue}
    }
    /// Returns true if `scanEntryFlags` has been explicitly set.
    var hasScanEntryFlags: Bool {return self._scanEntryFlags != nil}
    /// Clears the value of `scanEntryFlags`. Subsequent reads from it will return its default value.
    mutating func clearScanEntryFlags() {self._scanEntryFlags = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _ssid: String? = nil
    fileprivate var _signalStrengthBars: Int32? = nil
    fileprivate var _signalFrequencyMhz: Int32? = nil
    fileprivate var _scanEntryFlags: Int32? = nil
  }

  init() {}

  fileprivate var _result: OpenGopro_EnumResultGeneric? = nil
  fileprivate var _scanID: Int32? = nil
}

///*
/// The current scanning state.
///
/// This is the initial response to a @ref RequestStartScan
struct OpenGopro_ResponseStartScanning: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Generic pass/fail/error info
  var result: OpenGopro_EnumResultGeneric {
    get {return _result ?? .resultUnknown}
    set {_result = newValue}
  }
  /// Returns true if `result` has been explicitly set.
  var hasResult: Bool {return self._result != nil}
  /// Clears the value of `result`. Subsequent reads from it will return its default value.
  mutating func clearResult() {self._result = nil}

  /// Scanning state
  var scanningState: OpenGopro_EnumScanning {
    get {return _scanningState ?? .scanningUnknown}
    set {_scanningState = newValue}
  }
  /// Returns true if `scanningState` has been explicitly set.
  var hasScanningState: Bool {return self._scanningState != nil}
  /// Clears the value of `scanningState`. Subsequent reads from it will return its default value.
  mutating func clearScanningState() {self._scanningState = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _result: OpenGopro_EnumResultGeneric? = nil
  fileprivate var _scanningState: OpenGopro_EnumScanning? = nil
}

///*
/// Set Wireless 2.0 Pairing State
///
/// This is often colloquially referred to as "sending pairing complete"
///
/// Response: @ref ResponseGeneric
struct OpenGopro_RequestPairingFinish: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Pairing state to set
  var result: OpenGopro_EnumPairingFinishState {
    get {return _result ?? .success}
    set {_result = newValue}
  }
  /// Returns true if `result` has been explicitly set.
  var hasResult: Bool {return self._result != nil}
  /// Clears the value of `result`. Subsequent reads from it will return its default value.
  mutating func clearResult() {self._result = nil}

  ///*
  /// This must be a non empty string but it does not actually affect anything.
  var phoneName: String {
    get {return _phoneName ?? String()}
    set {_phoneName = newValue}
  }
  /// Returns true if `phoneName` has been explicitly set.
  var hasPhoneName: Bool {return self._phoneName != nil}
  /// Clears the value of `phoneName`. Subsequent reads from it will return its default value.
  mutating func clearPhoneName() {self._phoneName = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _result: OpenGopro_EnumPairingFinishState? = nil
  fileprivate var _phoneName: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "open_gopro"

extension OpenGopro_EnumProvisioning: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0PROVISIONING_UNKNOWN\0\u{1}PROVISIONING_NEVER_STARTED\0\u{1}PROVISIONING_STARTED\0\u{1}PROVISIONING_ABORTED_BY_SYSTEM\0\u{1}PROVISIONING_CANCELLED_BY_USER\0\u{1}PROVISIONING_SUCCESS_NEW_AP\0\u{1}PROVISIONING_SUCCESS_OLD_AP\0\u{1}PROVISIONING_ERROR_FAILED_TO_ASSOCIATE\0\u{1}PROVISIONING_ERROR_PASSWORD_AUTH\0\u{1}PROVISIONING_ERROR_EULA_BLOCKING\0\u{1}PROVISIONING_ERROR_NO_INTERNET\0\u{1}PROVISIONING_ERROR_UNSUPPORTED_TYPE\0")
}

extension OpenGopro_EnumScanning: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0SCANNING_UNKNOWN\0\u{1}SCANNING_NEVER_STARTED\0\u{1}SCANNING_STARTED\0\u{1}SCANNING_ABORTED_BY_SYSTEM\0\u{1}SCANNING_CANCELLED_BY_USER\0\u{1}SCANNING_SUCCESS\0")
}

extension OpenGopro_EnumScanEntryFlags: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0SCAN_FLAG_OPEN\0\u{1}SCAN_FLAG_AUTHENTICATED\0\u{1}SCAN_FLAG_CONFIGURED\0\u{2}\u{2}SCAN_FLAG_BEST_SSID\0\u{2}\u{4}SCAN_FLAG_ASSOCIATED\0\u{2}\u{8}SCAN_FLAG_UNSUPPORTED_TYPE\0")
}

extension OpenGopro_EnumPairingFinishState: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0SUCCESS\0\u{1}FAILED\0")
}

extension OpenGopro_NotifProvisioningState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".NotifProvisioningState"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}provisioning_state\0")

  public var isInitialized: Bool {
    if self._provisioningState == nil {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._provisioningState) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._provisioningState {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: OpenGopro_NotifProvisioningState, rhs: OpenGopro_NotifProvisioningState) -> Bool {
    if lhs._provisioningState != rhs._provisioningState {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension OpenGopro_NotifStartScanning: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".NotifStartScanning"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}scanning_state\0\u{3}scan_id\0\u{3}total_entries\0\u{3}total_configured_ssid\0")

  public var isInitialized: Bool {
    if self._scanningState == nil {return false}
    if self._totalConfiguredSsid == nil {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._scanningState) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._scanID) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self._totalEntries) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self._totalConfiguredSsid) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._scanningState {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._scanID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._totalEntries {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._totalConfiguredSsid {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: OpenGopro_NotifStartScanning, rhs: OpenGopro_NotifStartScanning) -> Bool {
    if lhs._scanningState != rhs._scanningState {return false}
    if lhs._scanID != rhs._scanID {return false}
    if lhs._totalEntries != rhs._totalEntries {return false}
    if lhs._totalConfiguredSsid != rhs._totalConfiguredSsid {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension OpenGopro_RequestConnect: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RequestConnect"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ssid\0")

  public var isInitialized: Bool {
    if self._ssid == nil {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._ssid) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._ssid {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: OpenGopro_RequestConnect, rhs: OpenGopro_RequestConnect) -> Bool {
    if lhs._ssid != rhs._ssid {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension OpenGopro_RequestConnectNew: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RequestConnectNew"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ssid\0\u{1}password\0\u{3}static_ip\0\u{1}gateway\0\u{1}subnet\0\u{3}dns_primary\0\u{3}dns_secondary\0\u{4}\u{3}bypass_eula_check\0")

  public var isInitialized: Bool {
    if self._ssid == nil {return false}
    if self._password == nil {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._ssid) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._password) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self._staticIp) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self._gateway) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self._subnet) }()
      case 6: try { try decoder.decodeSingularBytesField(value: &self._dnsPrimary) }()
      case 7: try { try decoder.decodeSingularBytesField(value: &self._dnsSecondary) }()
      case 10: try { try decoder.decodeSingularBoolField(value: &self._bypassEulaCheck) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._ssid {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._password {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._staticIp {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._gateway {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._subnet {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._dnsPrimary {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._dnsSecondary {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._bypassEulaCheck {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 10)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: OpenGopro_RequestConnectNew, rhs: OpenGopro_RequestConnectNew) -> Bool {
    if lhs._ssid != rhs._ssid {return false}
    if lhs._password != rhs._password {return false}
    if lhs._staticIp != rhs._staticIp {return false}
    if lhs._gateway != rhs._gateway {return false}
    if lhs._subnet != rhs._subnet {return false}
    if lhs._dnsPrimary != rhs._dnsPrimary {return false}
    if lhs._dnsSecondary != rhs._dnsSecondary {return false}
    if lhs._bypassEulaCheck != rhs._bypassEulaCheck {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension OpenGopro_RequestGetApEntries: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RequestGetApEntries"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}start_index\0\u{3}max_entries\0\u{3}scan_id\0")

  public var isInitialized: Bool {
    if self._startIndex == nil {return false}
    if self._maxEntries == nil {return false}
    if self._scanID == nil {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._startIndex) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._maxEntries) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self._scanID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._startIndex {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._maxEntries {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._scanID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: OpenGopro_RequestGetApEntries, rhs: OpenGopro_RequestGetApEntries) -> Bool {
    if lhs._startIndex != rhs._startIndex {return false}
    if lhs._maxEntries != rhs._maxEntries {return false}
    if lhs._scanID != rhs._scanID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension OpenGopro_RequestReleaseNetwork: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RequestReleaseNetwork"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: OpenGopro_RequestReleaseNetwork, rhs: OpenGopro_RequestReleaseNetwork) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension OpenGopro_RequestStartScan: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RequestStartScan"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: OpenGopro_RequestStartScan, rhs: OpenGopro_RequestStartScan) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension OpenGopro_ResponseConnect: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ResponseConnect"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}result\0\u{3}provisioning_state\0\u{3}timeout_seconds\0")

  public var isInitialized: Bool {
    if self._result == nil {return false}
    if self._provisioningState == nil {return false}
    if self._timeoutSeconds == nil {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._result) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self._provisioningState) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self._timeoutSeconds) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._result {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._provisioningState {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._timeoutSeconds {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: OpenGopro_ResponseConnect, rhs: OpenGopro_ResponseConnect) -> Bool {
    if lhs._result != rhs._result {return false}
    if lhs._provisioningState != rhs._provisioningState {return false}
    if lhs._timeoutSeconds != rhs._timeoutSeconds {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension OpenGopro_ResponseConnectNew: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ResponseConnectNew"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}result\0\u{3}provisioning_state\0\u{3}timeout_seconds\0")

  public var isInitialized: Bool {
    if self._result == nil {return false}
    if self._provisioningState == nil {return false}
    if self._timeoutSeconds == nil {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._result) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self._provisioningState) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self._timeoutSeconds) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._result {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._provisioningState {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._timeoutSeconds {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: OpenGopro_ResponseConnectNew, rhs: OpenGopro_ResponseConnectNew) -> Bool {
    if lhs._result != rhs._result {return false}
    if lhs._provisioningState != rhs._provisioningState {return false}
    if lhs._timeoutSeconds != rhs._timeoutSeconds {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension OpenGopro_ResponseGetApEntries: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ResponseGetApEntries"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}result\0\u{3}scan_id\0\u{1}entries\0")

  public var isInitialized: Bool {
    if self._result == nil {return false}
    if self._scanID == nil {return false}
    if !SwiftProtobuf.Internal.areAllInitialized(self.entries) {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._result) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._scanID) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.entries) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._result {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._scanID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    if !self.entries.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.entries, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: OpenGopro_ResponseGetApEntries, rhs: OpenGopro_ResponseGetApEntries) -> Bool {
    if lhs._result != rhs._result {return false}
    if lhs._scanID != rhs._scanID {return false}
    if lhs.entries != rhs.entries {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension OpenGopro_ResponseGetApEntries.ScanEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = OpenGopro_ResponseGetApEntries.protoMessageName + ".ScanEntry"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ssid\0\u{3}signal_strength_bars\0\u{4}\u{2}signal_frequency_mhz\0\u{3}scan_entry_flags\0")

  public var isInitialized: Bool {
    if self._ssid == nil {return false}
    if self._signalStrengthBars == nil {return false}
    if self._signalFrequencyMhz == nil {return false}
    if self._scanEntryFlags == nil {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._ssid) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._signalStrengthBars) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self._signalFrequencyMhz) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self._scanEntryFlags) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._ssid {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._signalStrengthBars {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._signalFrequencyMhz {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._scanEntryFlags {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: OpenGopro_ResponseGetApEntries.ScanEntry, rhs: OpenGopro_ResponseGetApEntries.ScanEntry) -> Bool {
    if lhs._ssid != rhs._ssid {return false}
    if lhs._signalStrengthBars != rhs._signalStrengthBars {return false}
    if lhs._signalFrequencyMhz != rhs._signalFrequencyMhz {return false}
    if lhs._scanEntryFlags != rhs._scanEntryFlags {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension OpenGopro_ResponseStartScanning: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ResponseStartScanning"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}result\0\u{3}scanning_state\0")

  public var isInitialized: Bool {
    if self._result == nil {return false}
    if self._scanningState == nil {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._result) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self._scanningState) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._result {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._scanningState {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: OpenGopro_ResponseStartScanning, rhs: OpenGopro_ResponseStartScanning) -> Bool {
    if lhs._result != rhs._result {return false}
    if lhs._scanningState != rhs._scanningState {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension OpenGopro_RequestPairingFinish: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RequestPairingFinish"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}result\0\u{1}phoneName\0")

  public var isInitialized: Bool {
    if self._result == nil {return false}
    if self._phoneName == nil {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._result) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._phoneName) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._result {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._phoneName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: OpenGopro_RequestPairingFinish, rhs: OpenGopro_RequestPairingFinish) -> Bool {
    if lhs._result != rhs._result {return false}
    if lhs._phoneName != rhs._phoneName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
