// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: response_generic.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// response_generic.proto/Open GoPro, Version 2.0 (C) Copyright 2021 GoPro, Inc. (http://gopro.com/OpenGoPro). 

// This copyright was auto-generated on Mon Nov  4 18:00:55 UTC 2024 

//**********************************************************************************************************************
//
// This file is automatically generated!!! Do not modify manually.
//
//********************************************************************************************************************

//*
// Defines the structure of protobuf message containing generic response to a command

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum OpenGopro_EnumResultGeneric: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
  case resultUnknown = 0
  case resultSuccess = 1
  case resultIllFormed = 2
  case resultNotSupported = 3
  case resultArgumentOutOfBounds = 4
  case resultArgumentInvalid = 5
  case resultResourceNotAvailable = 6

  init() {
    self = .resultUnknown
  }

}

///
/// Generic Response used across many response / notification messages
struct OpenGopro_ResponseGeneric: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Generic pass/fail/error info
  var result: OpenGopro_EnumResultGeneric {
    get {return _result ?? .resultUnknown}
    set {_result = newValue}
  }
  /// Returns true if `result` has been explicitly set.
  var hasResult: Bool {return self._result != nil}
  /// Clears the value of `result`. Subsequent reads from it will return its default value.
  mutating func clearResult() {self._result = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _result: OpenGopro_EnumResultGeneric? = nil
}

///*
/// A common model to represent a media file
struct OpenGopro_Media: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Directory in which the media is contained
  var folder: String {
    get {return _folder ?? String()}
    set {_folder = newValue}
  }
  /// Returns true if `folder` has been explicitly set.
  var hasFolder: Bool {return self._folder != nil}
  /// Clears the value of `folder`. Subsequent reads from it will return its default value.
  mutating func clearFolder() {self._folder = nil}

  /// Filename of media
  var file: String {
    get {return _file ?? String()}
    set {_file = newValue}
  }
  /// Returns true if `file` has been explicitly set.
  var hasFile: Bool {return self._file != nil}
  /// Clears the value of `file`. Subsequent reads from it will return its default value.
  mutating func clearFile() {self._file = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _folder: String? = nil
  fileprivate var _file: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "open_gopro"

extension OpenGopro_EnumResultGeneric: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0RESULT_UNKNOWN\0\u{1}RESULT_SUCCESS\0\u{1}RESULT_ILL_FORMED\0\u{1}RESULT_NOT_SUPPORTED\0\u{1}RESULT_ARGUMENT_OUT_OF_BOUNDS\0\u{1}RESULT_ARGUMENT_INVALID\0\u{1}RESULT_RESOURCE_NOT_AVAILABLE\0")
}

extension OpenGopro_ResponseGeneric: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ResponseGeneric"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}result\0")

  public var isInitialized: Bool {
    if self._result == nil {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._result) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._result {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: OpenGopro_ResponseGeneric, rhs: OpenGopro_ResponseGeneric) -> Bool {
    if lhs._result != rhs._result {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension OpenGopro_Media: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Media"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}folder\0\u{1}file\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._folder) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._file) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._folder {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._file {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: OpenGopro_Media, rhs: OpenGopro_Media) -> Bool {
    if lhs._folder != rhs._folder {return false}
    if lhs._file != rhs._file {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
