import json
from pathlib import Path
from typing import Literal
from typing import TypedDict
from typing import cast


class StringUnit(TypedDict):
    state: Literal["new", "needs_review", "translated"]
    value: str


class Localization(TypedDict):
    stringUnit: StringUnit


Localizations = dict[str, Localization]


class CatalogString(TypedDict, total=False):
    comment: str
    localizations: Localizations
    extractionState: str
    shouldTranslate: bool
    isCommentAutoGenerated: bool


class Catalog(TypedDict):
    sourceLanguage: str
    strings: dict[str, CatalogString]
    version: str


def load(path: Path) -> Catalog:
    return cast(Catalog, json.loads(path.read_text(encoding="utf-8")))


def store(path: Path, catalog: Catalog) -> None:
    path.write_text(
        json.dumps(catalog, indent=2, ensure_ascii=False, separators=(",", " : ")),
        encoding="utf-8",
    )
