import json
from dataclasses import dataclass
from pathlib import Path
from typing import Literal
from typing import TypedDict
from typing import cast


class StringUnit(TypedDict):
    state: Literal["new", "needs_review", "translated"]
    value: str


class Localization(TypedDict):
    stringUnit: StringUnit


Localizations = dict[str, Localization]


class CatalogString(TypedDict, total=False):
    comment: str
    localizations: Localizations
    extractionState: str
    shouldTranslate: bool
    isCommentAutoGenerated: bool


class CatalogData(TypedDict):
    sourceLanguage: str
    strings: dict[str, CatalogString]
    version: str


@dataclass
class Catalog:
    path: Path
    data: CatalogData

    @staticmethod
    def load(path: Path) -> "Catalog":
        return Catalog(path, cast(CatalogData, json.loads(path.read_text(encoding="utf-8"))))

    def store(self) -> None:
        self.path.write_text(
            json.dumps(self.data, indent=2, ensure_ascii=False, separators=(",", " : ")),
            encoding="utf-8",
        )

    @property
    def strings(self) -> dict[str, CatalogString]:
        return self.data["strings"]
