// This file is dynamically generated by the iOS app server.
// It exports the WebSocket port that the server is listening on.
// During development, you can set a port manually here.
export const websocketPort = 8081;
